help (
[[
This module loads VASPKIT.
Version 1.5.1
]])

if mode() == "load" then
  LmodMessage("-------------------------| Help message for VASPKIT module |-------------------------------")
  LmodMessage("If you are running VASPKIT for a first time, please copy the configuration file to your HOME directory by typing:")
  LmodMessage("cp $VASPKIT_CONFIG $HOME/.vaspkit")
  LmodMessage("Next, please modify the parameters in $HOME/.vaspkit based on your data.")
  LmodMessage("-------------------------------------------------------------------------------------------")
end

whatis("Name: VASPKIT")
whatis("Version: 1.5.1")
whatis("Category: Chemistry, VASP")
whatis("Keywords: VASP, analyses, raw data")
whatis("URL: https://vaspkit.com/index.html")
whatis("Description: Perform high throughput analysis from data generated by VASP.")

pushenv("VASPKIT_CONFIG", "/util/opt/anaconda/deployed-conda-envs/packages/vaspkit/envs/vaspkit-1.5.1/share/vaspkit-1.5.1-0/vaspkit_config")

pushenv("CONDA_DEFAULT_ENV", "vaspkit-1.5.1")
prepend_path("PATH", "/util/opt/anaconda/deployed-conda-envs/packages/vaspkit/envs/vaspkit-1.5.1/bin")
append_path("CONDA_ENVS_PATH", "/util/opt/anaconda/deployed-conda-envs/packages/vaspkit/envs")

family("python")
