variables:
  WORK: "/tmp"
  LMOD_REDIRECT: "yes"
  MODULES_DIR: "/util/opt/hcc-modules"
  LMOD_HOME: "/util/opt/lmod/lmod"

stages:
  - test
  - deploy

test-modules:
  stage: test
  image: unlhcc/crane-build-el8
  except:
    - master
  tags:
    - docker
  before_script:
    - source $LMOD_HOME/init/profile
  script:
    - module use $CI_PROJECT_DIR/Common
    - module av > /dev/null
    - module spider > /dev/null

test-swan-paths:
  stage: test
  image: unlhcc/swan-build
  except:
    - master
  tags:
    - swan
  script:
    - scripts/test_changed_modules.sh

deploy-swan:
  stage: deploy
  environment:
    name: swan_production
    url: https://swan.unl.edu
  resource_group: production-swan
  image: unlhcc/swan-build
  only:
    - master
  tags:
    - swan
  before_script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
    - source $LMOD_HOME/init/profile
    - module load lmod
  script:
    - cd $MODULES_DIR
    - git checkout master
    - git fetch
    - git checkout $CI_COMMIT_SHA
    - update_lmod_system_cache_files -d $MODULES_DIR/cacheDir -t $MODULES_DIR/cacheTS.txt $MODULES_DIR
  after_script:
    - scripts/replace_software_keys.sh
