variables:
  WORK: "/tmp"
  LMOD_REDIRECT: "yes"
  MODULES_DIR: "/util/opt/hcc-modules"

stages:
  - test
  - deploy
  - sync-to-github

test-modules:
  stage: test
  image: unlhcc/crane-build-el6
  except:
    - master
  tags:
    - docker
  before_script:
    - source /util/opt/lmod/lmod/init/profile
  script:
    - module use $CI_PROJECT_DIR/Common
    - module av > /dev/null
    - module spider > /dev/null

test-crane-paths:
  stage: test
  image: unlhcc/crane-build-el6
  except:
    - master
  tags:
    - crane-test
  script:
    - scripts/test_changed_modules.sh

#test-tusker-paths:
#  stage: test
#  image: unlhcc/crane-build-el6
#  except:
#    - master
#  tags:
#    - tusker-test
#  script:
#    - scripts/test_changed_modules.sh

deploy-crane:
  stage: deploy
  environment:
    name: crane_production
    url: https://crane.unl.edu
  image: unlhcc/crane-build-el6
  only:
    - master
  tags:
    - crane
  before_script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
  script:
    - cd $MODULES_DIR
    - git checkout master
    - git fetch
    - git checkout $CI_COMMIT_SHA

#deploy-tusker:
#  stage: deploy
#  environment:
#    name: tusker_production
#    url: https://tusker.unl.edu
#  image: unlhcc/crane-build-el6
#  only:
#    - master
#  tags:
#    - tusker
#  before_script:
#    - eval $(ssh-agent -s) > /dev/null
#    - mkdir -p ~/.ssh
#    - chown 700 ~/.ssh
#    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
#    - chmod 644 ~/.ssh/known_hosts
#    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
#  script:
#    - cd $MODULES_DIR
#    - git checkout master
#    - git fetch
#    - git checkout $CI_COMMIT_SHA

sync-to-github:
  stage: sync-to-github
  tags:
    - docker
  image: unlhcc/crane-build-el6
  allow_failure: yes
  only:
    - master
  script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $GITHUB_SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$GITHUB_SSH_DEPLOY_PKEY" | base64 --decode)
    - git config user.name "HCC Gitlab CI"
    - git config user.email "hcc-support@unl.edu"
    - git checkout master
    - git remote add github git@github.com:unlhcc/hcc-modules.git
    - git push github +master
