help(
[[
This module loads TransDecoder.

Version 3.0.1
]]
)

whatis("Name: TransDecoder")
whatis("Version: 3.0.1")
whatis("Category: computational biology, genomics")
whatis("Keywords: Biology, Genomics, Assembly, RNASeq, Transcriptome Profiling")
whatis("URL: https://transdecoder.github.io")
whatis("Description: TransDecoder identifies candidate coding regions within transcript sequences, such as those generated by de novo RNA-Seq transcript assembly using Trinity, or constructed based on RNA-Seq alignments to the genome using Tophat and Cufflinks.")

pushenv("CONDA_DEFAULT_ENV","transdecoder-3.0.1")
prepend_path{"PATH","/util/opt/anaconda/deployed-conda-envs/packages/transdecoder/envs/transdecoder-3.0.1/bin",priority=100}
append_path("CONDA_ENVS_PATH", "/util/opt/anaconda/deployed-conda-envs/packages/transdecoder/envs")
