help (
[[
This module loads the environment for static data resources, e.g. BLAST databases, KEGG, Genomes, 
short read aligner indicies, etc. 

Many environment variables will be pre-set, but likely you only need a subset of them. Environment
variables can be used in your command lines or scripts by prefixing a $ sign to the name. For example,

      module load bowtie/2.2
      bowtie2 -x $BOWTIE2_HORSE  -U my_sample.fq -S my_sample.sam

will run the bowtie2 command utilizing the default Horse (Equus caballus) index. 


The major environment variables are:

$DATA             Main database directory
$BLAST            Main BLAST database directory (>= blast 2.10)
$BLAST_V4         Archived BLAST version 4 databases (blast <= 2.9)
$KEGG             KEGG database main entry point (requires license)
$PANTHER          PANTHER database main entry point (latest)
$IPR              InterProScan database main entry point (latest)
$IMG_VR           IMG VR database main entry point (latest)
$GENOMES          Directory containing all available genomes (multiple sources, builds possible)
$INDICES          Directory containing indices for bowtie, bowtie2, bwa for all available genomes
$UNIPROT          Directory containing latest release of full UniProt database
$TAXONOMY         Directory containing latest release of NCBO Taxonomy database
$QIIME_DB_DIR     Directory containing releases of taxonomic databases Greengenes and Silva

You can alsways check what's available by, e.g.

ls $GENOMES

or:

find $GENOMES -type d


For the genomes and indices, direct access points are set up to much used files or directories. The 
structure of the environment variable is as follows:

     $<SECTION>_<SCIENTIFIC NAME>_<SOURCE>_<BUILD>

* SECTION determines the type of underlying file(s) or directory. The following sections are available:
        GENOME       points to full genome FASTA file
        CHR          points to directory containing individual FASTAs for each chromosome
        PICARD       points to a Picard compatible .dict file
        FAIDX        points to a FASTA index file .fai (used in samtools, amongst others)
        BOWTIE       points to the bowtie index base (part of filename that bowtie will expand)
        BOWTIE2      points to the bowtie2 index base (part of filename that bowtie2 will expand)
        BWA          points to the bwa index base (part of filename that bwa will expand)

* SCIENTIFIC_NAME is the full scientific name (with spaces replaced by an underscore).
        Can also be a common name; if so please note that it will point to the DEFAULT source and build version
        that is set on the system. 

* SOURCE is the source of the genome assembly and annotation from which all SECTIONs originate.
        Can be one of the following: Illumina, NCBI, Ensembl, or UCSC.

* BUILD is the name and version of the specific genome assembly/annotation.

For those species where a common name is available in the system, there is a shortcut by using <SECTION>_<COMMON NAME>.
However, please note that these point to a DEFAULT source and build as specified by the system, e.g. $GENOME_DOG. If only
one source and/or build is available for that species, it doesn't matter, but if multiple sources/builds are available the
system has picked something that might not be the source and build you want to use. You can check what such a default points to
by typing, e.g.:

echo $GENOME_DOG

and that will give you the full source + build version location.


Examples of these environment variables:

$GENOME_YEAST
$GENOME_SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3.1
$GENOME_SACCHAROMYCES_CEREVISIAE_ENSEMBL_EF4
$CHR_HORSE
$BOWTIE2_PIG
$BWA_ATH
$PICARD_BOS_TAURUS_ENSEMBL_UMD3.1
$FAIDX_MAIZE

There are some shortcuts that point directly to BACTERIAL and ARCHAE genomic resources from NCBI. They
are as follows (with $GENOME_* pointing to the FASTA file):

$BLAST_BACTERIAL, $BWA_BACTERIAL, $BOWTIE2_BACTERIAL, 
		$GENOME_BACTERIAL, $FAIDX_BACTERIAL	All _complete_ bacterial genomes
$BLAST_BACTERIAL_ALL, $BWA_BACTERIAL_ALL, $BOWTIE2_BACTERIAL_ALL, 
		$GENOME_BACTERIAL_ALL, $FAIDX_BACTERIAL_ALL	All bacterial genomes (incl. incomplete)
$BLAST_ARCHAEA, $BWA_ARCHAEA, $BOWTIE2_ARCHAEA, 
		$GENOME_ARCHAEA, $FAIDX_ARCHAEA	All _complete_ archaea genomes
$BLAST_ARCHAEA_ALL, $BWA_ARCHAEA_ALL, $BOWTIE2_ARCHAEA_ALL, 
		$GENOME_ARCHAEA_ALL, $FAIDX_ARCHAEA_ALL	All archaea genomes (incl. incomplete)

######################################################################
                 INSTALLLED SPECIES	(COMMON NAME/SHORTCUT)
######################################################################
               ARABIDOPSIS_THALIANA	(ATH)
         BACILLUS_CEREUS_ATCC_10987	
              BACILLUS_SUBTILIS_168	(BSUBT_168)
         BOS_GRUNNIENS_X_BOS_TAURUS	
                         BOS_TAURUS	(COW)
             CAENORHABDITIS_ELEGANS	(CELEGANS)
                   CANIS_FAMILIARIS	(DOG)
                        DANIO_RERIO	
            DROSOPHILA_MELANOGASTER	
         ENTEROBACTERIOPHAGE_LAMBDA	(ELAMBDA)
                     EQUUS_CABALLUS	(HORSE)
        ESCHERICHIA_COLI_K_12_DH10B	
       ESCHERICHIA_COLI_K_12_MG1655	
                      GALLUS_GALLUS	(CHICKEN)
                        GLYCINE_MAX	(SOYBEAN)
                       HOMO_SAPIENS	(HUMAN)
         ICTIDOMYS_TRIDECEMLINEATUS	(SQUIRREL)
                     MACACA_MULATTA	
                       MUS_MUSCULUS	(MOUSE)
   MYCOBACTERIUM_TUBERCULOSIS_H37RV	
                    OAR_RAMBOUILLET	
              ORYZA_SATIVA_JAPONICA	(RICE)
                         OVIS_ARIES	(SHEEP)
                    PAN_TROGLODYTES	
                               PHIX	
        PSEUDOMONAS_AERUGINOSA_PAO1	
                  RATTUS_NORVEGICUS	(RAT)
           SACCHAROMYCES_CEREVISIAE	(YEAST)
               SCIURUS_CAROLINENSIS	
                   SCIURUS_VULGARIS	
                    SORGHUM_BICOLOR	(SORGHUM)
    STAPHYLOCOCCUS_AUREUS_NCTC_8325	
                         SUS_SCROFA	(PIG)
                           ZEA_MAYS	(MAIZE)


Version 1.0
]])



whatis("Name: biodata")
whatis("Version: 1.0")
whatis("Category: computational biology, sequence analysis, databases")
whatis("Keywords: Biology, Genomics")
whatis("Description: Static data resources for bioinformatics/computational biology.")

---------------------------------------------------------------------------------------------------------
-- Some of the resources below are set up to use local variables as well to enable pathJoin() operations
-- to section or versions of databases.
---------------------------------------------------------------------------------------------------------



-- High level entry points to data resources
local data = "/work/HCC/BCRF"
local genomes = pathJoin(data, "Genomes")
local indices = pathJoin(data, "indices")
local bowtie2 = pathJoin(indices, "bowtie2")
local bowtie = pathJoin(indices, "bowtie")
local bwa = pathJoin(indices, "bwa")
local blast = pathJoin(data, "BLAST")
local blast_v4 = pathJoin(blast, "v4")
local uniprot_root = pathJoin(data, "uniprot")
local metaphlan_root = pathJoin(data, "metaphlan")
local kegg = pathJoin(data, "kegg")
local ipr_root = pathJoin(data, "interproscan")
local panther_root = pathJoin(data, "panther")
local img_vr_root = pathJoin(data, "img_vr")
local taxon_root = pathJoin(data, "taxonomy")
local app = "/work/HCC/BCRF/app_specific"
local orthodb_root = pathJoin(app, "busco/orthodb")
local humann2_root = pathJoin(app, "humann2")


pushenv("DATA", data)
pushenv("KEGG", kegg)
pushenv("GENOMES", genomes)
pushenv("BLAST", blast)
pushenv("BLAST_V4", blast_v4)
pushenv("INDICES", indices)
pushenv("INDICES_BOWTIE", bowtie)
pushenv("INDICES_BOWTIE2", bowtie2)
pushenv("INDICES_BWA", bwa)
pushenv("APP", app)


-- Most recent versions of major databases (where appropiate)
local panther_latest = "9.0"
local ipr_latest = "5"
local metaphlan_latest = "2.6"
local humann2_latest = "0.11.2"
local orthodb_latest = "v10"
local uniprot_latest = "latest"
local img_vr_latest = "latest"
local uniref_root = pathJoin(uniprot_root, uniprot_latest, "uniref")
local metaphlan_latest_root = pathJoin(metaphlan_root, metaphlan_latest)
local orthodb_latest_root = pathJoin(orthodb_root, orthodb_latest)
local humann2_latest_root = pathJoin(humann2_root, humann2_latest)
local img_vr_latest_root = pathJoin(img_vr_root, img_vr_latest)
local qiime_db = "/work/HCC/BCRF/app_specific/qiime/"
pushenv("IPR", pathJoin(ipr_root, ipr_latest))
pushenv("PANTHER", pathJoin(panther_root, panther_latest))
pushenv("UNIPROT", pathJoin(uniprot_root, uniprot_latest))
pushenv("UNIPROT_KB", pathJoin(uniprot_root, uniprot_latest, "knowledgebase"))
pushenv("UNIPROT_UNIREF", uniref_root)
pushenv("UNIPROT_UNIREF100", pathJoin(uniref_root, "uniref100/uniref100.fasta"))
pushenv("UNIPROT_UNIREF90", pathJoin(uniref_root, "uniref90/uniref90.fasta"))
pushenv("UNIPROT_UNIREF50", pathJoin(uniref_root, "uniref50/uniref50.fasta"))
pushenv("METAPHLAN", metaphlan_latest_root)
pushenv("METAPHLAN_BLAST", pathJoin(metaphlan_latest_root, "blastdb/mpa"))
pushenv("METAPHLAN_BOWTIE", pathJoin(metaphlan_latest_root, "bowtie2db/mpa"))
pushenv("TAXONOMY", taxon_root)
pushenv("TAXONOMY_NAMES", pathJoin(taxon_root, "names.dmp"))
pushenv("TAXONOMY_NODES", pathJoin(taxon_root, "nodes.dmp"))
pushenv("ORTHODB", orthodb_latest_root)
pushenv("ORTHODB_V9", pathJoin(orthodb_root, "v9/"))
pushenv("ORTHODB_V10", pathJoin(orthodb_root, "v10/"))
pushenv("HUMANN2", humann2_latest_root)
pushenv("IMG_VR", img_vr_latest_root)
pushenv("IMG_VR_PROT", pathJoin(blast, "IMG_VR_prot"))
pushenv("IMG_VR_NUCL", pathJoin(blast, "IMG_VR_nucl"))
pushenv("QIIME_DB_DIR", qiime_db)
pushenv("SILVA", pathJoin(qiime_db, "silva-132-99-515-806-nb-classifier.qza"))
pushenv("SILVA_132_99_515_806", pathJoin(qiime_db, "silva-132-99-515-806-nb-classifier.qza"))
pushenv("SILVA_132_99_FULL_LENGTH", pathJoin(qiime_db, "silva-132-99-nb-classifier.qza"))
pushenv("GREENGENES", pathJoin(qiime_db, "gg-13-8-99-515-806-nb-classifier.qza"))
pushenv("GREENGENES_13_8_99_515_806", pathJoin(qiime_db, "gg-13-8-99-515-806-nb-classifier.qza"))
pushenv("GREENGENES_13_8_99_FULL_LENGTH", pathJoin(qiime_db, "gg-13-8-99-nb-classifier.qza"))


-- Genome databases and indices
local _w = "WholeGenomeFasta"
local _c = "Chromosomes"
local _f = "genome.fa"
local _p = "genome.dict"
local _s = "genome.fa.fai"
local _gs = "GenomeSize.xml"
local _b = "genome"
local _bwa = "genome.fa"
-- Note: defaults have a short name, all other versions of a genome/index
--       are listed with their long name, in the following format:
--       <SECTION>_<SCIENTIFIC_NAME>_<SOURCE>_<BUILD>
--       where SECTION is GENOME, BOWTIE, BOWTIE2, BWA, etc.
pushenv ("ATH", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10"))
pushenv ("GENOME_ATH", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10", _w, _f))
pushenv ("CHR_ATH", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10", _c))
pushenv ("BOWTIE_ATH", pathJoin(bowtie, "Arabidopsis_thaliana", "NCBI", "TAIR10", _b))
pushenv ("BOWTIE2_ATH", pathJoin(bowtie2, "Arabidopsis_thaliana", "NCBI", "TAIR10", _b))
pushenv ("BWA_ATH", pathJoin(bwa, "Arabidopsis_thaliana", "NCBI", "TAIR10", _bwa))
pushenv ("PICARD_ATH", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10", _w, _p))
pushenv ("FAIDX_ATH", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10", _w, _s))
pushenv ("ARABIDOPSIS_THALIANA_NCBI_TAIR10", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10"))
pushenv ("GENOME_ARABIDOPSIS_THALIANA_NCBI_TAIR10", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10", _w, _f))
pushenv ("CHR_ARABIDOPSIS_THALIANA_NCBI_TAIR10", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10", _c))
pushenv ("BOWTIE_ARABIDOPSIS_THALIANA_NCBI_TAIR10", pathJoin(bowtie, "Arabidopsis_thaliana", "NCBI", "TAIR10", _b))
pushenv ("BOWTIE2_ARABIDOPSIS_THALIANA_NCBI_TAIR10", pathJoin(bowtie2, "Arabidopsis_thaliana", "NCBI", "TAIR10", _b))
pushenv ("BWA_ARABIDOPSIS_THALIANA_NCBI_TAIR10", pathJoin(bwa, "Arabidopsis_thaliana", "NCBI", "TAIR10", _bwa))
pushenv ("PICARD_ARABIDOPSIS_THALIANA_NCBI_TAIR10", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10", _w, _p))
pushenv ("FAIDX_ARABIDOPSIS_THALIANA_NCBI_TAIR10", pathJoin(genomes, "Arabidopsis_thaliana", "NCBI", "TAIR10", _w, _s))
pushenv ("BACILLUS_CEREUS_ATCC_10987", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13"))
pushenv ("GENOME_BACILLUS_CEREUS_ATCC_10987", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _w, _f))
pushenv ("CHR_BACILLUS_CEREUS_ATCC_10987", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _c))
pushenv ("BOWTIE_BACILLUS_CEREUS_ATCC_10987", pathJoin(bowtie, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _b))
pushenv ("BOWTIE2_BACILLUS_CEREUS_ATCC_10987", pathJoin(bowtie2, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _b))
pushenv ("BWA_BACILLUS_CEREUS_ATCC_10987", pathJoin(bwa, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _bwa))
pushenv ("PICARD_BACILLUS_CEREUS_ATCC_10987", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _w, _p))
pushenv ("FAIDX_BACILLUS_CEREUS_ATCC_10987", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _w, _s))
pushenv ("BACILLUS_CEREUS_ATCC_10987_NCBI_2004_02_13", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13"))
pushenv ("GENOME_BACILLUS_CEREUS_ATCC_10987_NCBI_2004_02_13", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _w, _f))
pushenv ("CHR_BACILLUS_CEREUS_ATCC_10987_NCBI_2004_02_13", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _c))
pushenv ("BOWTIE_BACILLUS_CEREUS_ATCC_10987_NCBI_2004_02_13", pathJoin(bowtie, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _b))
pushenv ("BOWTIE2_BACILLUS_CEREUS_ATCC_10987_NCBI_2004_02_13", pathJoin(bowtie2, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _b))
pushenv ("BWA_BACILLUS_CEREUS_ATCC_10987_NCBI_2004_02_13", pathJoin(bwa, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _bwa))
pushenv ("PICARD_BACILLUS_CEREUS_ATCC_10987_NCBI_2004_02_13", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _w, _p))
pushenv ("FAIDX_BACILLUS_CEREUS_ATCC_10987_NCBI_2004_02_13", pathJoin(genomes, "Bacillus_cereus_ATCC_10987", "NCBI", "2004-02-13", _w, _s))
pushenv ("BSUBT_168", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2"))
pushenv ("GENOME_BSUBT_168", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2", _w, _f))
pushenv ("CHR_BSUBT_168", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2", _c))
pushenv ("BOWTIE_BSUBT_168", pathJoin(bowtie, "Bacillus_subtilis_168", "Ensembl", "EB2", _b))
pushenv ("BOWTIE2_BSUBT_168", pathJoin(bowtie2, "Bacillus_subtilis_168", "Ensembl", "EB2", _b))
pushenv ("BWA_BSUBT_168", pathJoin(bwa, "Bacillus_subtilis_168", "Ensembl", "EB2", _bwa))
pushenv ("PICARD_BSUBT_168", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2", _w, _p))
pushenv ("FAIDX_BSUBT_168", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2", _w, _s))
pushenv ("BACILLUS_SUBTILIS_168_ENSEMBL_EB2", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2"))
pushenv ("GENOME_BACILLUS_SUBTILIS_168_ENSEMBL_EB2", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2", _w, _f))
pushenv ("CHR_BACILLUS_SUBTILIS_168_ENSEMBL_EB2", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2", _c))
pushenv ("BOWTIE_BACILLUS_SUBTILIS_168_ENSEMBL_EB2", pathJoin(bowtie, "Bacillus_subtilis_168", "Ensembl", "EB2", _b))
pushenv ("BOWTIE2_BACILLUS_SUBTILIS_168_ENSEMBL_EB2", pathJoin(bowtie2, "Bacillus_subtilis_168", "Ensembl", "EB2", _b))
pushenv ("BWA_BACILLUS_SUBTILIS_168_ENSEMBL_EB2", pathJoin(bwa, "Bacillus_subtilis_168", "Ensembl", "EB2", _bwa))
pushenv ("PICARD_BACILLUS_SUBTILIS_168_ENSEMBL_EB2", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2", _w, _p))
pushenv ("FAIDX_BACILLUS_SUBTILIS_168_ENSEMBL_EB2", pathJoin(genomes, "Bacillus_subtilis_168", "Ensembl", "EB2", _w, _s))
pushenv ("BOS_GRUNNIENS_X_BOS_TAURUS", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1"))
pushenv ("GENOME_BOS_GRUNNIENS_X_BOS_TAURUS", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _w, _f))
pushenv ("CHR_BOS_GRUNNIENS_X_BOS_TAURUS", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _c))
pushenv ("BOWTIE_BOS_GRUNNIENS_X_BOS_TAURUS", pathJoin(bowtie, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _b))
pushenv ("BOWTIE2_BOS_GRUNNIENS_X_BOS_TAURUS", pathJoin(bowtie2, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _b))
pushenv ("BWA_BOS_GRUNNIENS_X_BOS_TAURUS", pathJoin(bwa, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _bwa))
pushenv ("PICARD_BOS_GRUNNIENS_X_BOS_TAURUS", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _w, _p))
pushenv ("FAIDX_BOS_GRUNNIENS_X_BOS_TAURUS", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _w, _s))
pushenv ("BOS_GRUNNIENS_X_BOS_TAURUS_NCBI_1", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1"))
pushenv ("GENOME_BOS_GRUNNIENS_X_BOS_TAURUS_NCBI_1", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _w, _f))
pushenv ("CHR_BOS_GRUNNIENS_X_BOS_TAURUS_NCBI_1", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _c))
pushenv ("BOWTIE_BOS_GRUNNIENS_X_BOS_TAURUS_NCBI_1", pathJoin(bowtie, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _b))
pushenv ("BOWTIE2_BOS_GRUNNIENS_X_BOS_TAURUS_NCBI_1", pathJoin(bowtie2, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _b))
pushenv ("BWA_BOS_GRUNNIENS_X_BOS_TAURUS_NCBI_1", pathJoin(bwa, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _bwa))
pushenv ("PICARD_BOS_GRUNNIENS_X_BOS_TAURUS_NCBI_1", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _w, _p))
pushenv ("FAIDX_BOS_GRUNNIENS_X_BOS_TAURUS_NCBI_1", pathJoin(genomes, "Bos_grunniens_x_Bos_taurus", "NCBI", "1", _w, _s))
pushenv ("BOS_TAURUS_ENSEMBL_UMD3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD3.1"))
pushenv ("GENOME_BOS_TAURUS_ENSEMBL_UMD3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD3.1", _w, _f))
pushenv ("CHR_BOS_TAURUS_ENSEMBL_UMD3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD3.1", _c))
pushenv ("BOWTIE_BOS_TAURUS_ENSEMBL_UMD3_1", pathJoin(bowtie, "Bos_taurus", "Ensembl", "UMD3.1", _b))
pushenv ("BOWTIE2_BOS_TAURUS_ENSEMBL_UMD3_1", pathJoin(bowtie2, "Bos_taurus", "Ensembl", "UMD3.1", _b))
pushenv ("BWA_BOS_TAURUS_ENSEMBL_UMD3_1", pathJoin(bwa, "Bos_taurus", "Ensembl", "UMD3.1", _bwa))
pushenv ("PICARD_BOS_TAURUS_ENSEMBL_UMD3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD3.1", _w, _p))
pushenv ("FAIDX_BOS_TAURUS_ENSEMBL_UMD3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD3.1", _w, _s))
pushenv ("BOS_TAURUS_ENSEMBL_UMD_3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD_3.1"))
pushenv ("GENOME_BOS_TAURUS_ENSEMBL_UMD_3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD_3.1", _w, _f))
pushenv ("CHR_BOS_TAURUS_ENSEMBL_UMD_3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD_3.1", _c))
pushenv ("BOWTIE_BOS_TAURUS_ENSEMBL_UMD_3_1", pathJoin(bowtie, "Bos_taurus", "Ensembl", "UMD_3.1", _b))
pushenv ("BOWTIE2_BOS_TAURUS_ENSEMBL_UMD_3_1", pathJoin(bowtie2, "Bos_taurus", "Ensembl", "UMD_3.1", _b))
pushenv ("BWA_BOS_TAURUS_ENSEMBL_UMD_3_1", pathJoin(bwa, "Bos_taurus", "Ensembl", "UMD_3.1", _bwa))
pushenv ("PICARD_BOS_TAURUS_ENSEMBL_UMD_3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD_3.1", _w, _p))
pushenv ("FAIDX_BOS_TAURUS_ENSEMBL_UMD_3_1", pathJoin(genomes, "Bos_taurus", "Ensembl", "UMD_3.1", _w, _s))
pushenv ("BOS_TAURUS_NCBI_ARS_UCD1_2", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2"))
pushenv ("GENOME_BOS_TAURUS_NCBI_ARS_UCD1_2", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2", _w, _f))
pushenv ("CHR_BOS_TAURUS_NCBI_ARS_UCD1_2", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2", _c))
pushenv ("BOWTIE_BOS_TAURUS_NCBI_ARS_UCD1_2", pathJoin(bowtie, "Bos_taurus", "NCBI", "ARS-UCD1.2", _b))
pushenv ("BOWTIE2_BOS_TAURUS_NCBI_ARS_UCD1_2", pathJoin(bowtie2, "Bos_taurus", "NCBI", "ARS-UCD1.2", _b))
pushenv ("BWA_BOS_TAURUS_NCBI_ARS_UCD1_2", pathJoin(bwa, "Bos_taurus", "NCBI", "ARS-UCD1.2", _bwa))
pushenv ("PICARD_BOS_TAURUS_NCBI_ARS_UCD1_2", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2", _w, _p))
pushenv ("FAIDX_BOS_TAURUS_NCBI_ARS_UCD1_2", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2", _w, _s))
pushenv ("COW", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced"))
pushenv ("GENOME_COW", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _w, _f))
pushenv ("CHR_COW", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _c))
pushenv ("BOWTIE_COW", pathJoin(bowtie, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _b))
pushenv ("BOWTIE2_COW", pathJoin(bowtie2, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _b))
pushenv ("BWA_COW", pathJoin(bwa, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _bwa))
pushenv ("PICARD_COW", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _w, _p))
pushenv ("FAIDX_COW", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _w, _s))
pushenv ("BOS_TAURUS_NCBI_ARS_UCD1_2_NO_UNPLACED", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced"))
pushenv ("GENOME_BOS_TAURUS_NCBI_ARS_UCD1_2_NO_UNPLACED", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _w, _f))
pushenv ("CHR_BOS_TAURUS_NCBI_ARS_UCD1_2_NO_UNPLACED", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _c))
pushenv ("BOWTIE_BOS_TAURUS_NCBI_ARS_UCD1_2_NO_UNPLACED", pathJoin(bowtie, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _b))
pushenv ("BOWTIE2_BOS_TAURUS_NCBI_ARS_UCD1_2_NO_UNPLACED", pathJoin(bowtie2, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _b))
pushenv ("BWA_BOS_TAURUS_NCBI_ARS_UCD1_2_NO_UNPLACED", pathJoin(bwa, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _bwa))
pushenv ("PICARD_BOS_TAURUS_NCBI_ARS_UCD1_2_NO_UNPLACED", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _w, _p))
pushenv ("FAIDX_BOS_TAURUS_NCBI_ARS_UCD1_2_NO_UNPLACED", pathJoin(genomes, "Bos_taurus", "NCBI", "ARS-UCD1.2-no_unplaced", _w, _s))
pushenv ("BOS_TAURUS_NCBI_UMD_3_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1"))
pushenv ("GENOME_BOS_TAURUS_NCBI_UMD_3_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1", _w, _f))
pushenv ("CHR_BOS_TAURUS_NCBI_UMD_3_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1", _c))
pushenv ("BOWTIE_BOS_TAURUS_NCBI_UMD_3_1", pathJoin(bowtie, "Bos_taurus", "NCBI", "UMD_3.1", _b))
pushenv ("BOWTIE2_BOS_TAURUS_NCBI_UMD_3_1", pathJoin(bowtie2, "Bos_taurus", "NCBI", "UMD_3.1", _b))
pushenv ("BWA_BOS_TAURUS_NCBI_UMD_3_1", pathJoin(bwa, "Bos_taurus", "NCBI", "UMD_3.1", _bwa))
pushenv ("PICARD_BOS_TAURUS_NCBI_UMD_3_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1", _w, _p))
pushenv ("FAIDX_BOS_TAURUS_NCBI_UMD_3_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1", _w, _s))
pushenv ("BOS_TAURUS_NCBI_UMD_3_1_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1.1"))
pushenv ("GENOME_BOS_TAURUS_NCBI_UMD_3_1_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1.1", _w, _f))
pushenv ("CHR_BOS_TAURUS_NCBI_UMD_3_1_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1.1", _c))
pushenv ("BOWTIE_BOS_TAURUS_NCBI_UMD_3_1_1", pathJoin(bowtie, "Bos_taurus", "NCBI", "UMD_3.1.1", _b))
pushenv ("BOWTIE2_BOS_TAURUS_NCBI_UMD_3_1_1", pathJoin(bowtie2, "Bos_taurus", "NCBI", "UMD_3.1.1", _b))
pushenv ("BWA_BOS_TAURUS_NCBI_UMD_3_1_1", pathJoin(bwa, "Bos_taurus", "NCBI", "UMD_3.1.1", _bwa))
pushenv ("PICARD_BOS_TAURUS_NCBI_UMD_3_1_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1.1", _w, _p))
pushenv ("FAIDX_BOS_TAURUS_NCBI_UMD_3_1_1", pathJoin(genomes, "Bos_taurus", "NCBI", "UMD_3.1.1", _w, _s))
pushenv ("CELEGANS", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195"))
pushenv ("GENOME_CELEGANS", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195", _w, _f))
pushenv ("CHR_CELEGANS", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195", _c))
pushenv ("BOWTIE_CELEGANS", pathJoin(bowtie, "Caenorhabditis_elegans", "NCBI", "WS195", _b))
pushenv ("BOWTIE2_CELEGANS", pathJoin(bowtie2, "Caenorhabditis_elegans", "NCBI", "WS195", _b))
pushenv ("BWA_CELEGANS", pathJoin(bwa, "Caenorhabditis_elegans", "NCBI", "WS195", _bwa))
pushenv ("PICARD_CELEGANS", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195", _w, _p))
pushenv ("FAIDX_CELEGANS", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195", _w, _s))
pushenv ("CAENORHABDITIS_ELEGANS_NCBI_WS195", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195"))
pushenv ("GENOME_CAENORHABDITIS_ELEGANS_NCBI_WS195", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195", _w, _f))
pushenv ("CHR_CAENORHABDITIS_ELEGANS_NCBI_WS195", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195", _c))
pushenv ("BOWTIE_CAENORHABDITIS_ELEGANS_NCBI_WS195", pathJoin(bowtie, "Caenorhabditis_elegans", "NCBI", "WS195", _b))
pushenv ("BOWTIE2_CAENORHABDITIS_ELEGANS_NCBI_WS195", pathJoin(bowtie2, "Caenorhabditis_elegans", "NCBI", "WS195", _b))
pushenv ("BWA_CAENORHABDITIS_ELEGANS_NCBI_WS195", pathJoin(bwa, "Caenorhabditis_elegans", "NCBI", "WS195", _bwa))
pushenv ("PICARD_CAENORHABDITIS_ELEGANS_NCBI_WS195", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195", _w, _p))
pushenv ("FAIDX_CAENORHABDITIS_ELEGANS_NCBI_WS195", pathJoin(genomes, "Caenorhabditis_elegans", "NCBI", "WS195", _w, _s))
pushenv ("DOG", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1"))
pushenv ("GENOME_DOG", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1", _w, _f))
pushenv ("CHR_DOG", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1", _c))
pushenv ("BOWTIE_DOG", pathJoin(bowtie, "Canis_familiaris", "NCBI", "build3.1", _b))
pushenv ("BOWTIE2_DOG", pathJoin(bowtie2, "Canis_familiaris", "NCBI", "build3.1", _b))
pushenv ("BWA_DOG", pathJoin(bwa, "Canis_familiaris", "NCBI", "build3.1", _bwa))
pushenv ("PICARD_DOG", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1", _w, _p))
pushenv ("FAIDX_DOG", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1", _w, _s))
pushenv ("CANIS_FAMILIARIS_NCBI_BUILD3_1", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1"))
pushenv ("GENOME_CANIS_FAMILIARIS_NCBI_BUILD3_1", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1", _w, _f))
pushenv ("CHR_CANIS_FAMILIARIS_NCBI_BUILD3_1", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1", _c))
pushenv ("BOWTIE_CANIS_FAMILIARIS_NCBI_BUILD3_1", pathJoin(bowtie, "Canis_familiaris", "NCBI", "build3.1", _b))
pushenv ("BOWTIE2_CANIS_FAMILIARIS_NCBI_BUILD3_1", pathJoin(bowtie2, "Canis_familiaris", "NCBI", "build3.1", _b))
pushenv ("BWA_CANIS_FAMILIARIS_NCBI_BUILD3_1", pathJoin(bwa, "Canis_familiaris", "NCBI", "build3.1", _bwa))
pushenv ("PICARD_CANIS_FAMILIARIS_NCBI_BUILD3_1", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1", _w, _p))
pushenv ("FAIDX_CANIS_FAMILIARIS_NCBI_BUILD3_1", pathJoin(genomes, "Canis_familiaris", "NCBI", "build3.1", _w, _s))
pushenv ("DANIO_RERIO", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9"))
pushenv ("GENOME_DANIO_RERIO", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9", _w, _f))
pushenv ("CHR_DANIO_RERIO", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9", _c))
pushenv ("BOWTIE_DANIO_RERIO", pathJoin(bowtie, "Danio_rerio", "NCBI", "Zv9", _b))
pushenv ("BOWTIE2_DANIO_RERIO", pathJoin(bowtie2, "Danio_rerio", "NCBI", "Zv9", _b))
pushenv ("BWA_DANIO_RERIO", pathJoin(bwa, "Danio_rerio", "NCBI", "Zv9", _bwa))
pushenv ("PICARD_DANIO_RERIO", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9", _w, _p))
pushenv ("FAIDX_DANIO_RERIO", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9", _w, _s))
pushenv ("DANIO_RERIO_NCBI_ZV9", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9"))
pushenv ("GENOME_DANIO_RERIO_NCBI_ZV9", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9", _w, _f))
pushenv ("CHR_DANIO_RERIO_NCBI_ZV9", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9", _c))
pushenv ("BOWTIE_DANIO_RERIO_NCBI_ZV9", pathJoin(bowtie, "Danio_rerio", "NCBI", "Zv9", _b))
pushenv ("BOWTIE2_DANIO_RERIO_NCBI_ZV9", pathJoin(bowtie2, "Danio_rerio", "NCBI", "Zv9", _b))
pushenv ("BWA_DANIO_RERIO_NCBI_ZV9", pathJoin(bwa, "Danio_rerio", "NCBI", "Zv9", _bwa))
pushenv ("PICARD_DANIO_RERIO_NCBI_ZV9", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9", _w, _p))
pushenv ("FAIDX_DANIO_RERIO_NCBI_ZV9", pathJoin(genomes, "Danio_rerio", "NCBI", "Zv9", _w, _s))
pushenv ("DROSOPHILA_MELANOGASTER", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41"))
pushenv ("GENOME_DROSOPHILA_MELANOGASTER", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41", _w, _f))
pushenv ("CHR_DROSOPHILA_MELANOGASTER", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41", _c))
pushenv ("BOWTIE_DROSOPHILA_MELANOGASTER", pathJoin(bowtie, "Drosophila_melanogaster", "NCBI", "build5.41", _b))
pushenv ("BOWTIE2_DROSOPHILA_MELANOGASTER", pathJoin(bowtie2, "Drosophila_melanogaster", "NCBI", "build5.41", _b))
pushenv ("BWA_DROSOPHILA_MELANOGASTER", pathJoin(bwa, "Drosophila_melanogaster", "NCBI", "build5.41", _bwa))
pushenv ("PICARD_DROSOPHILA_MELANOGASTER", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41", _w, _p))
pushenv ("FAIDX_DROSOPHILA_MELANOGASTER", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41", _w, _s))
pushenv ("DROSOPHILA_MELANOGASTER_NCBI_BUILD5_41", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41"))
pushenv ("GENOME_DROSOPHILA_MELANOGASTER_NCBI_BUILD5_41", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41", _w, _f))
pushenv ("CHR_DROSOPHILA_MELANOGASTER_NCBI_BUILD5_41", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41", _c))
pushenv ("BOWTIE_DROSOPHILA_MELANOGASTER_NCBI_BUILD5_41", pathJoin(bowtie, "Drosophila_melanogaster", "NCBI", "build5.41", _b))
pushenv ("BOWTIE2_DROSOPHILA_MELANOGASTER_NCBI_BUILD5_41", pathJoin(bowtie2, "Drosophila_melanogaster", "NCBI", "build5.41", _b))
pushenv ("BWA_DROSOPHILA_MELANOGASTER_NCBI_BUILD5_41", pathJoin(bwa, "Drosophila_melanogaster", "NCBI", "build5.41", _bwa))
pushenv ("PICARD_DROSOPHILA_MELANOGASTER_NCBI_BUILD5_41", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41", _w, _p))
pushenv ("FAIDX_DROSOPHILA_MELANOGASTER_NCBI_BUILD5_41", pathJoin(genomes, "Drosophila_melanogaster", "NCBI", "build5.41", _w, _s))
pushenv ("ELAMBDA", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28"))
pushenv ("GENOME_ELAMBDA", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _w, _f))
pushenv ("CHR_ELAMBDA", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _c))
pushenv ("BOWTIE_ELAMBDA", pathJoin(bowtie, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _b))
pushenv ("BOWTIE2_ELAMBDA", pathJoin(bowtie2, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _b))
pushenv ("BWA_ELAMBDA", pathJoin(bwa, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _bwa))
pushenv ("PICARD_ELAMBDA", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _w, _p))
pushenv ("FAIDX_ELAMBDA", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _w, _s))
pushenv ("ENTEROBACTERIOPHAGE_LAMBDA_NCBI_1993_04_28", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28"))
pushenv ("GENOME_ENTEROBACTERIOPHAGE_LAMBDA_NCBI_1993_04_28", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _w, _f))
pushenv ("CHR_ENTEROBACTERIOPHAGE_LAMBDA_NCBI_1993_04_28", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _c))
pushenv ("BOWTIE_ENTEROBACTERIOPHAGE_LAMBDA_NCBI_1993_04_28", pathJoin(bowtie, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _b))
pushenv ("BOWTIE2_ENTEROBACTERIOPHAGE_LAMBDA_NCBI_1993_04_28", pathJoin(bowtie2, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _b))
pushenv ("BWA_ENTEROBACTERIOPHAGE_LAMBDA_NCBI_1993_04_28", pathJoin(bwa, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _bwa))
pushenv ("PICARD_ENTEROBACTERIOPHAGE_LAMBDA_NCBI_1993_04_28", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _w, _p))
pushenv ("FAIDX_ENTEROBACTERIOPHAGE_LAMBDA_NCBI_1993_04_28", pathJoin(genomes, "Enterobacteriophage_lambda", "NCBI", "1993-04-28", _w, _s))
pushenv ("EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0"))
pushenv ("GENOME_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0", _w, _f))
pushenv ("CHR_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0", _c))
pushenv ("BOWTIE_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0", pathJoin(bowtie, "Equus_caballus", "Ensembl", "EquCab3.0", _b))
pushenv ("BOWTIE2_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0", pathJoin(bowtie2, "Equus_caballus", "Ensembl", "EquCab3.0", _b))
pushenv ("BWA_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0", pathJoin(bwa, "Equus_caballus", "Ensembl", "EquCab3.0", _bwa))
pushenv ("PICARD_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0", _w, _p))
pushenv ("FAIDX_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0", _w, _s))
pushenv ("EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0_NO_UNPLACED", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0-no_unplaced"))
pushenv ("GENOME_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0_NO_UNPLACED", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0-no_unplaced", _w, _f))
pushenv ("CHR_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0_NO_UNPLACED", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0-no_unplaced", _c))
pushenv ("BOWTIE_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0_NO_UNPLACED", pathJoin(bowtie, "Equus_caballus", "Ensembl", "EquCab3.0-no_unplaced", _b))
pushenv ("BOWTIE2_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0_NO_UNPLACED", pathJoin(bowtie2, "Equus_caballus", "Ensembl", "EquCab3.0-no_unplaced", _b))
pushenv ("BWA_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0_NO_UNPLACED", pathJoin(bwa, "Equus_caballus", "Ensembl", "EquCab3.0-no_unplaced", _bwa))
pushenv ("PICARD_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0_NO_UNPLACED", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0-no_unplaced", _w, _p))
pushenv ("FAIDX_EQUUS_CABALLUS_ENSEMBL_EQUCAB3_0_NO_UNPLACED", pathJoin(genomes, "Equus_caballus", "Ensembl", "EquCab3.0-no_unplaced", _w, _s))
pushenv ("HORSE", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0"))
pushenv ("GENOME_HORSE", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0", _w, _f))
pushenv ("CHR_HORSE", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0", _c))
pushenv ("BOWTIE_HORSE", pathJoin(bowtie, "Equus_caballus", "NCBI", "EquCab2.0", _b))
pushenv ("BOWTIE2_HORSE", pathJoin(bowtie2, "Equus_caballus", "NCBI", "EquCab2.0", _b))
pushenv ("BWA_HORSE", pathJoin(bwa, "Equus_caballus", "NCBI", "EquCab2.0", _bwa))
pushenv ("PICARD_HORSE", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0", _w, _p))
pushenv ("FAIDX_HORSE", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0", _w, _s))
pushenv ("EQUUS_CABALLUS_NCBI_EQUCAB2_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0"))
pushenv ("GENOME_EQUUS_CABALLUS_NCBI_EQUCAB2_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0", _w, _f))
pushenv ("CHR_EQUUS_CABALLUS_NCBI_EQUCAB2_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0", _c))
pushenv ("BOWTIE_EQUUS_CABALLUS_NCBI_EQUCAB2_0", pathJoin(bowtie, "Equus_caballus", "NCBI", "EquCab2.0", _b))
pushenv ("BOWTIE2_EQUUS_CABALLUS_NCBI_EQUCAB2_0", pathJoin(bowtie2, "Equus_caballus", "NCBI", "EquCab2.0", _b))
pushenv ("BWA_EQUUS_CABALLUS_NCBI_EQUCAB2_0", pathJoin(bwa, "Equus_caballus", "NCBI", "EquCab2.0", _bwa))
pushenv ("PICARD_EQUUS_CABALLUS_NCBI_EQUCAB2_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0", _w, _p))
pushenv ("FAIDX_EQUUS_CABALLUS_NCBI_EQUCAB2_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab2.0", _w, _s))
pushenv ("EQUUS_CABALLUS_NCBI_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab3.0"))
pushenv ("GENOME_EQUUS_CABALLUS_NCBI_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab3.0", _w, _f))
pushenv ("CHR_EQUUS_CABALLUS_NCBI_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab3.0", _c))
pushenv ("BOWTIE_EQUUS_CABALLUS_NCBI_EQUCAB3_0", pathJoin(bowtie, "Equus_caballus", "NCBI", "EquCab3.0", _b))
pushenv ("BOWTIE2_EQUUS_CABALLUS_NCBI_EQUCAB3_0", pathJoin(bowtie2, "Equus_caballus", "NCBI", "EquCab3.0", _b))
pushenv ("BWA_EQUUS_CABALLUS_NCBI_EQUCAB3_0", pathJoin(bwa, "Equus_caballus", "NCBI", "EquCab3.0", _bwa))
pushenv ("PICARD_EQUUS_CABALLUS_NCBI_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab3.0", _w, _p))
pushenv ("FAIDX_EQUUS_CABALLUS_NCBI_EQUCAB3_0", pathJoin(genomes, "Equus_caballus", "NCBI", "EquCab3.0", _w, _s))
pushenv ("ESCHERICHIA_COLI_K_12_DH10B", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17"))
pushenv ("GENOME_ESCHERICHIA_COLI_K_12_DH10B", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _w, _f))
pushenv ("CHR_ESCHERICHIA_COLI_K_12_DH10B", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _c))
pushenv ("BOWTIE_ESCHERICHIA_COLI_K_12_DH10B", pathJoin(bowtie, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _b))
pushenv ("BOWTIE2_ESCHERICHIA_COLI_K_12_DH10B", pathJoin(bowtie2, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _b))
pushenv ("BWA_ESCHERICHIA_COLI_K_12_DH10B", pathJoin(bwa, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _bwa))
pushenv ("PICARD_ESCHERICHIA_COLI_K_12_DH10B", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _w, _p))
pushenv ("FAIDX_ESCHERICHIA_COLI_K_12_DH10B", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _w, _s))
pushenv ("ESCHERICHIA_COLI_K_12_DH10B_NCBI_2008_03_17", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17"))
pushenv ("GENOME_ESCHERICHIA_COLI_K_12_DH10B_NCBI_2008_03_17", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _w, _f))
pushenv ("CHR_ESCHERICHIA_COLI_K_12_DH10B_NCBI_2008_03_17", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _c))
pushenv ("BOWTIE_ESCHERICHIA_COLI_K_12_DH10B_NCBI_2008_03_17", pathJoin(bowtie, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _b))
pushenv ("BOWTIE2_ESCHERICHIA_COLI_K_12_DH10B_NCBI_2008_03_17", pathJoin(bowtie2, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _b))
pushenv ("BWA_ESCHERICHIA_COLI_K_12_DH10B_NCBI_2008_03_17", pathJoin(bwa, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _bwa))
pushenv ("PICARD_ESCHERICHIA_COLI_K_12_DH10B_NCBI_2008_03_17", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _w, _p))
pushenv ("FAIDX_ESCHERICHIA_COLI_K_12_DH10B_NCBI_2008_03_17", pathJoin(genomes, "Escherichia_coli_K_12_DH10B", "NCBI", "2008-03-17", _w, _s))
pushenv ("ESCHERICHIA_COLI_K_12_MG1655", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15"))
pushenv ("GENOME_ESCHERICHIA_COLI_K_12_MG1655", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _w, _f))
pushenv ("CHR_ESCHERICHIA_COLI_K_12_MG1655", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _c))
pushenv ("BOWTIE_ESCHERICHIA_COLI_K_12_MG1655", pathJoin(bowtie, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _b))
pushenv ("BOWTIE2_ESCHERICHIA_COLI_K_12_MG1655", pathJoin(bowtie2, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _b))
pushenv ("BWA_ESCHERICHIA_COLI_K_12_MG1655", pathJoin(bwa, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _bwa))
pushenv ("PICARD_ESCHERICHIA_COLI_K_12_MG1655", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _w, _p))
pushenv ("FAIDX_ESCHERICHIA_COLI_K_12_MG1655", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _w, _s))
pushenv ("ESCHERICHIA_COLI_K_12_MG1655_NCBI_2001_10_15", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15"))
pushenv ("GENOME_ESCHERICHIA_COLI_K_12_MG1655_NCBI_2001_10_15", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _w, _f))
pushenv ("CHR_ESCHERICHIA_COLI_K_12_MG1655_NCBI_2001_10_15", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _c))
pushenv ("BOWTIE_ESCHERICHIA_COLI_K_12_MG1655_NCBI_2001_10_15", pathJoin(bowtie, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _b))
pushenv ("BOWTIE2_ESCHERICHIA_COLI_K_12_MG1655_NCBI_2001_10_15", pathJoin(bowtie2, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _b))
pushenv ("BWA_ESCHERICHIA_COLI_K_12_MG1655_NCBI_2001_10_15", pathJoin(bwa, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _bwa))
pushenv ("PICARD_ESCHERICHIA_COLI_K_12_MG1655_NCBI_2001_10_15", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _w, _p))
pushenv ("FAIDX_ESCHERICHIA_COLI_K_12_MG1655_NCBI_2001_10_15", pathJoin(genomes, "Escherichia_coli_K_12_MG1655", "NCBI", "2001-10-15", _w, _s))
pushenv ("CHICKEN", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a"))
pushenv ("GENOME_CHICKEN", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a", _w, _f))
pushenv ("CHR_CHICKEN", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a", _c))
pushenv ("BOWTIE_CHICKEN", pathJoin(bowtie, "Gallus_gallus", "NCBI", "GRCg6a", _b))
pushenv ("BOWTIE2_CHICKEN", pathJoin(bowtie2, "Gallus_gallus", "NCBI", "GRCg6a", _b))
pushenv ("BWA_CHICKEN", pathJoin(bwa, "Gallus_gallus", "NCBI", "GRCg6a", _bwa))
pushenv ("PICARD_CHICKEN", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a", _w, _p))
pushenv ("FAIDX_CHICKEN", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a", _w, _s))
pushenv ("GALLUS_GALLUS_NCBI_GRCG6A", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a"))
pushenv ("GENOME_GALLUS_GALLUS_NCBI_GRCG6A", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a", _w, _f))
pushenv ("CHR_GALLUS_GALLUS_NCBI_GRCG6A", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a", _c))
pushenv ("BOWTIE_GALLUS_GALLUS_NCBI_GRCG6A", pathJoin(bowtie, "Gallus_gallus", "NCBI", "GRCg6a", _b))
pushenv ("BOWTIE2_GALLUS_GALLUS_NCBI_GRCG6A", pathJoin(bowtie2, "Gallus_gallus", "NCBI", "GRCg6a", _b))
pushenv ("BWA_GALLUS_GALLUS_NCBI_GRCG6A", pathJoin(bwa, "Gallus_gallus", "NCBI", "GRCg6a", _bwa))
pushenv ("PICARD_GALLUS_GALLUS_NCBI_GRCG6A", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a", _w, _p))
pushenv ("FAIDX_GALLUS_GALLUS_NCBI_GRCG6A", pathJoin(genomes, "Gallus_gallus", "NCBI", "GRCg6a", _w, _s))
pushenv ("GALLUS_GALLUS_NCBI_BUILD3_1", pathJoin(genomes, "Gallus_gallus", "NCBI", "build3.1"))
pushenv ("GENOME_GALLUS_GALLUS_NCBI_BUILD3_1", pathJoin(genomes, "Gallus_gallus", "NCBI", "build3.1", _w, _f))
pushenv ("CHR_GALLUS_GALLUS_NCBI_BUILD3_1", pathJoin(genomes, "Gallus_gallus", "NCBI", "build3.1", _c))
pushenv ("BOWTIE_GALLUS_GALLUS_NCBI_BUILD3_1", pathJoin(bowtie, "Gallus_gallus", "NCBI", "build3.1", _b))
pushenv ("BOWTIE2_GALLUS_GALLUS_NCBI_BUILD3_1", pathJoin(bowtie2, "Gallus_gallus", "NCBI", "build3.1", _b))
pushenv ("BWA_GALLUS_GALLUS_NCBI_BUILD3_1", pathJoin(bwa, "Gallus_gallus", "NCBI", "build3.1", _bwa))
pushenv ("PICARD_GALLUS_GALLUS_NCBI_BUILD3_1", pathJoin(genomes, "Gallus_gallus", "NCBI", "build3.1", _w, _p))
pushenv ("FAIDX_GALLUS_GALLUS_NCBI_BUILD3_1", pathJoin(genomes, "Gallus_gallus", "NCBI", "build3.1", _w, _s))
pushenv ("GALLUS_GALLUS_UCSC_GALGAL4", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal4"))
pushenv ("GENOME_GALLUS_GALLUS_UCSC_GALGAL4", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal4", _w, _f))
pushenv ("CHR_GALLUS_GALLUS_UCSC_GALGAL4", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal4", _c))
pushenv ("BOWTIE_GALLUS_GALLUS_UCSC_GALGAL4", pathJoin(bowtie, "Gallus_gallus", "UCSC", "galGal4", _b))
pushenv ("BOWTIE2_GALLUS_GALLUS_UCSC_GALGAL4", pathJoin(bowtie2, "Gallus_gallus", "UCSC", "galGal4", _b))
pushenv ("BWA_GALLUS_GALLUS_UCSC_GALGAL4", pathJoin(bwa, "Gallus_gallus", "UCSC", "galGal4", _bwa))
pushenv ("PICARD_GALLUS_GALLUS_UCSC_GALGAL4", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal4", _w, _p))
pushenv ("FAIDX_GALLUS_GALLUS_UCSC_GALGAL4", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal4", _w, _s))
pushenv ("GALLUS_GALLUS_UCSC_GALGAL5", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal5"))
pushenv ("GENOME_GALLUS_GALLUS_UCSC_GALGAL5", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal5", _w, _f))
pushenv ("CHR_GALLUS_GALLUS_UCSC_GALGAL5", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal5", _c))
pushenv ("BOWTIE_GALLUS_GALLUS_UCSC_GALGAL5", pathJoin(bowtie, "Gallus_gallus", "UCSC", "galGal5", _b))
pushenv ("BOWTIE2_GALLUS_GALLUS_UCSC_GALGAL5", pathJoin(bowtie2, "Gallus_gallus", "UCSC", "galGal5", _b))
pushenv ("BWA_GALLUS_GALLUS_UCSC_GALGAL5", pathJoin(bwa, "Gallus_gallus", "UCSC", "galGal5", _bwa))
pushenv ("PICARD_GALLUS_GALLUS_UCSC_GALGAL5", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal5", _w, _p))
pushenv ("FAIDX_GALLUS_GALLUS_UCSC_GALGAL5", pathJoin(genomes, "Gallus_gallus", "UCSC", "galGal5", _w, _s))
pushenv ("SOYBEAN", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01"))
pushenv ("GENOME_SOYBEAN", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01", _w, _f))
pushenv ("CHR_SOYBEAN", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01", _c))
pushenv ("BOWTIE_SOYBEAN", pathJoin(bowtie, "Glycine_max", "Ensembl", "Gm01", _b))
pushenv ("BOWTIE2_SOYBEAN", pathJoin(bowtie2, "Glycine_max", "Ensembl", "Gm01", _b))
pushenv ("BWA_SOYBEAN", pathJoin(bwa, "Glycine_max", "Ensembl", "Gm01", _bwa))
pushenv ("PICARD_SOYBEAN", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01", _w, _p))
pushenv ("FAIDX_SOYBEAN", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01", _w, _s))
pushenv ("GLYCINE_MAX_ENSEMBL_GM01", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01"))
pushenv ("GENOME_GLYCINE_MAX_ENSEMBL_GM01", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01", _w, _f))
pushenv ("CHR_GLYCINE_MAX_ENSEMBL_GM01", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01", _c))
pushenv ("BOWTIE_GLYCINE_MAX_ENSEMBL_GM01", pathJoin(bowtie, "Glycine_max", "Ensembl", "Gm01", _b))
pushenv ("BOWTIE2_GLYCINE_MAX_ENSEMBL_GM01", pathJoin(bowtie2, "Glycine_max", "Ensembl", "Gm01", _b))
pushenv ("BWA_GLYCINE_MAX_ENSEMBL_GM01", pathJoin(bwa, "Glycine_max", "Ensembl", "Gm01", _bwa))
pushenv ("PICARD_GLYCINE_MAX_ENSEMBL_GM01", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01", _w, _p))
pushenv ("FAIDX_GLYCINE_MAX_ENSEMBL_GM01", pathJoin(genomes, "Glycine_max", "Ensembl", "Gm01", _w, _s))
pushenv ("HOMO_SAPIENS_ENSEMBL_GRCH37", pathJoin(genomes, "Homo_sapiens", "Ensembl", "GRCh37"))
pushenv ("GENOME_HOMO_SAPIENS_ENSEMBL_GRCH37", pathJoin(genomes, "Homo_sapiens", "Ensembl", "GRCh37", _w, _f))
pushenv ("CHR_HOMO_SAPIENS_ENSEMBL_GRCH37", pathJoin(genomes, "Homo_sapiens", "Ensembl", "GRCh37", _c))
pushenv ("BOWTIE_HOMO_SAPIENS_ENSEMBL_GRCH37", pathJoin(bowtie, "Homo_sapiens", "Ensembl", "GRCh37", _b))
pushenv ("BOWTIE2_HOMO_SAPIENS_ENSEMBL_GRCH37", pathJoin(bowtie2, "Homo_sapiens", "Ensembl", "GRCh37", _b))
pushenv ("BWA_HOMO_SAPIENS_ENSEMBL_GRCH37", pathJoin(bwa, "Homo_sapiens", "Ensembl", "GRCh37", _bwa))
pushenv ("PICARD_HOMO_SAPIENS_ENSEMBL_GRCH37", pathJoin(genomes, "Homo_sapiens", "Ensembl", "GRCh37", _w, _p))
pushenv ("FAIDX_HOMO_SAPIENS_ENSEMBL_GRCH37", pathJoin(genomes, "Homo_sapiens", "Ensembl", "GRCh37", _w, _s))
pushenv ("HUMAN", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38"))
pushenv ("GENOME_HUMAN", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38", _w, _f))
pushenv ("CHR_HUMAN", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38", _c))
pushenv ("BOWTIE_HUMAN", pathJoin(bowtie, "Homo_sapiens", "NCBI", "GRCh38", _b))
pushenv ("BOWTIE2_HUMAN", pathJoin(bowtie2, "Homo_sapiens", "NCBI", "GRCh38", _b))
pushenv ("BWA_HUMAN", pathJoin(bwa, "Homo_sapiens", "NCBI", "GRCh38", _bwa))
pushenv ("PICARD_HUMAN", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38", _w, _p))
pushenv ("FAIDX_HUMAN", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38", _w, _s))
pushenv ("HOMO_SAPIENS_NCBI_GRCH38", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38"))
pushenv ("GENOME_HOMO_SAPIENS_NCBI_GRCH38", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38", _w, _f))
pushenv ("CHR_HOMO_SAPIENS_NCBI_GRCH38", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38", _c))
pushenv ("BOWTIE_HOMO_SAPIENS_NCBI_GRCH38", pathJoin(bowtie, "Homo_sapiens", "NCBI", "GRCh38", _b))
pushenv ("BOWTIE2_HOMO_SAPIENS_NCBI_GRCH38", pathJoin(bowtie2, "Homo_sapiens", "NCBI", "GRCh38", _b))
pushenv ("BWA_HOMO_SAPIENS_NCBI_GRCH38", pathJoin(bwa, "Homo_sapiens", "NCBI", "GRCh38", _bwa))
pushenv ("PICARD_HOMO_SAPIENS_NCBI_GRCH38", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38", _w, _p))
pushenv ("FAIDX_HOMO_SAPIENS_NCBI_GRCH38", pathJoin(genomes, "Homo_sapiens", "NCBI", "GRCh38", _w, _s))
pushenv ("HOMO_SAPIENS_NCBI_BUILD37_2", pathJoin(genomes, "Homo_sapiens", "NCBI", "build37.2"))
pushenv ("GENOME_HOMO_SAPIENS_NCBI_BUILD37_2", pathJoin(genomes, "Homo_sapiens", "NCBI", "build37.2", _w, _f))
pushenv ("CHR_HOMO_SAPIENS_NCBI_BUILD37_2", pathJoin(genomes, "Homo_sapiens", "NCBI", "build37.2", _c))
pushenv ("BOWTIE_HOMO_SAPIENS_NCBI_BUILD37_2", pathJoin(bowtie, "Homo_sapiens", "NCBI", "build37.2", _b))
pushenv ("BOWTIE2_HOMO_SAPIENS_NCBI_BUILD37_2", pathJoin(bowtie2, "Homo_sapiens", "NCBI", "build37.2", _b))
pushenv ("BWA_HOMO_SAPIENS_NCBI_BUILD37_2", pathJoin(bwa, "Homo_sapiens", "NCBI", "build37.2", _bwa))
pushenv ("PICARD_HOMO_SAPIENS_NCBI_BUILD37_2", pathJoin(genomes, "Homo_sapiens", "NCBI", "build37.2", _w, _p))
pushenv ("FAIDX_HOMO_SAPIENS_NCBI_BUILD37_2", pathJoin(genomes, "Homo_sapiens", "NCBI", "build37.2", _w, _s))
pushenv ("HOMO_SAPIENS_UCSC_HG18", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg18"))
pushenv ("GENOME_HOMO_SAPIENS_UCSC_HG18", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg18", _w, _f))
pushenv ("CHR_HOMO_SAPIENS_UCSC_HG18", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg18", _c))
pushenv ("BOWTIE_HOMO_SAPIENS_UCSC_HG18", pathJoin(bowtie, "Homo_sapiens", "UCSC", "hg18", _b))
pushenv ("BOWTIE2_HOMO_SAPIENS_UCSC_HG18", pathJoin(bowtie2, "Homo_sapiens", "UCSC", "hg18", _b))
pushenv ("BWA_HOMO_SAPIENS_UCSC_HG18", pathJoin(bwa, "Homo_sapiens", "UCSC", "hg18", _bwa))
pushenv ("PICARD_HOMO_SAPIENS_UCSC_HG18", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg18", _w, _p))
pushenv ("FAIDX_HOMO_SAPIENS_UCSC_HG18", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg18", _w, _s))
pushenv ("HOMO_SAPIENS_UCSC_HG19", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg19"))
pushenv ("GENOME_HOMO_SAPIENS_UCSC_HG19", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg19", _w, _f))
pushenv ("CHR_HOMO_SAPIENS_UCSC_HG19", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg19", _c))
pushenv ("BOWTIE_HOMO_SAPIENS_UCSC_HG19", pathJoin(bowtie, "Homo_sapiens", "UCSC", "hg19", _b))
pushenv ("BOWTIE2_HOMO_SAPIENS_UCSC_HG19", pathJoin(bowtie2, "Homo_sapiens", "UCSC", "hg19", _b))
pushenv ("BWA_HOMO_SAPIENS_UCSC_HG19", pathJoin(bwa, "Homo_sapiens", "UCSC", "hg19", _bwa))
pushenv ("PICARD_HOMO_SAPIENS_UCSC_HG19", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg19", _w, _p))
pushenv ("FAIDX_HOMO_SAPIENS_UCSC_HG19", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg19", _w, _s))
pushenv ("HOMO_SAPIENS_UCSC_HG38", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg38"))
pushenv ("GENOME_HOMO_SAPIENS_UCSC_HG38", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg38", _w, _f))
pushenv ("CHR_HOMO_SAPIENS_UCSC_HG38", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg38", _c))
pushenv ("BOWTIE_HOMO_SAPIENS_UCSC_HG38", pathJoin(bowtie, "Homo_sapiens", "UCSC", "hg38", _b))
pushenv ("BOWTIE2_HOMO_SAPIENS_UCSC_HG38", pathJoin(bowtie2, "Homo_sapiens", "UCSC", "hg38", _b))
pushenv ("BWA_HOMO_SAPIENS_UCSC_HG38", pathJoin(bwa, "Homo_sapiens", "UCSC", "hg38", _bwa))
pushenv ("PICARD_HOMO_SAPIENS_UCSC_HG38", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg38", _w, _p))
pushenv ("FAIDX_HOMO_SAPIENS_UCSC_HG38", pathJoin(genomes, "Homo_sapiens", "UCSC", "hg38", _w, _s))
pushenv ("SQUIRREL", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0"))
pushenv ("GENOME_SQUIRREL", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _w, _f))
pushenv ("CHR_SQUIRREL", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _c))
pushenv ("BOWTIE_SQUIRREL", pathJoin(bowtie, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _b))
pushenv ("BOWTIE2_SQUIRREL", pathJoin(bowtie2, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _b))
pushenv ("BWA_SQUIRREL", pathJoin(bwa, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _bwa))
pushenv ("PICARD_SQUIRREL", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _w, _p))
pushenv ("FAIDX_SQUIRREL", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _w, _s))
pushenv ("ICTIDOMYS_TRIDECEMLINEATUS_NCBI_SPETRI2_0", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0"))
pushenv ("GENOME_ICTIDOMYS_TRIDECEMLINEATUS_NCBI_SPETRI2_0", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _w, _f))
pushenv ("CHR_ICTIDOMYS_TRIDECEMLINEATUS_NCBI_SPETRI2_0", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _c))
pushenv ("BOWTIE_ICTIDOMYS_TRIDECEMLINEATUS_NCBI_SPETRI2_0", pathJoin(bowtie, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _b))
pushenv ("BOWTIE2_ICTIDOMYS_TRIDECEMLINEATUS_NCBI_SPETRI2_0", pathJoin(bowtie2, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _b))
pushenv ("BWA_ICTIDOMYS_TRIDECEMLINEATUS_NCBI_SPETRI2_0", pathJoin(bwa, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _bwa))
pushenv ("PICARD_ICTIDOMYS_TRIDECEMLINEATUS_NCBI_SPETRI2_0", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _w, _p))
pushenv ("FAIDX_ICTIDOMYS_TRIDECEMLINEATUS_NCBI_SPETRI2_0", pathJoin(genomes, "Ictidomys_tridecemlineatus", "NCBI", "SpeTri2.0", _w, _s))
pushenv ("MACACA_MULATTA", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1"))
pushenv ("GENOME_MACACA_MULATTA", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1", _w, _f))
pushenv ("CHR_MACACA_MULATTA", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1", _c))
pushenv ("BOWTIE_MACACA_MULATTA", pathJoin(bowtie, "Macaca_mulatta", "Ensembl", "Mmul_1", _b))
pushenv ("BOWTIE2_MACACA_MULATTA", pathJoin(bowtie2, "Macaca_mulatta", "Ensembl", "Mmul_1", _b))
pushenv ("BWA_MACACA_MULATTA", pathJoin(bwa, "Macaca_mulatta", "Ensembl", "Mmul_1", _bwa))
pushenv ("PICARD_MACACA_MULATTA", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1", _w, _p))
pushenv ("FAIDX_MACACA_MULATTA", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1", _w, _s))
pushenv ("MACACA_MULATTA_ENSEMBL_MMUL_1", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1"))
pushenv ("GENOME_MACACA_MULATTA_ENSEMBL_MMUL_1", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1", _w, _f))
pushenv ("CHR_MACACA_MULATTA_ENSEMBL_MMUL_1", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1", _c))
pushenv ("BOWTIE_MACACA_MULATTA_ENSEMBL_MMUL_1", pathJoin(bowtie, "Macaca_mulatta", "Ensembl", "Mmul_1", _b))
pushenv ("BOWTIE2_MACACA_MULATTA_ENSEMBL_MMUL_1", pathJoin(bowtie2, "Macaca_mulatta", "Ensembl", "Mmul_1", _b))
pushenv ("BWA_MACACA_MULATTA_ENSEMBL_MMUL_1", pathJoin(bwa, "Macaca_mulatta", "Ensembl", "Mmul_1", _bwa))
pushenv ("PICARD_MACACA_MULATTA_ENSEMBL_MMUL_1", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1", _w, _p))
pushenv ("FAIDX_MACACA_MULATTA_ENSEMBL_MMUL_1", pathJoin(genomes, "Macaca_mulatta", "Ensembl", "Mmul_1", _w, _s))
pushenv ("MOUSE", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38"))
pushenv ("GENOME_MOUSE", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38", _w, _f))
pushenv ("CHR_MOUSE", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38", _c))
pushenv ("BOWTIE_MOUSE", pathJoin(bowtie, "Mus_musculus", "NCBI", "GRCm38", _b))
pushenv ("BOWTIE2_MOUSE", pathJoin(bowtie2, "Mus_musculus", "NCBI", "GRCm38", _b))
pushenv ("BWA_MOUSE", pathJoin(bwa, "Mus_musculus", "NCBI", "GRCm38", _bwa))
pushenv ("PICARD_MOUSE", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38", _w, _p))
pushenv ("FAIDX_MOUSE", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38", _w, _s))
pushenv ("MUS_MUSCULUS_NCBI_GRCM38", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38"))
pushenv ("GENOME_MUS_MUSCULUS_NCBI_GRCM38", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38", _w, _f))
pushenv ("CHR_MUS_MUSCULUS_NCBI_GRCM38", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38", _c))
pushenv ("BOWTIE_MUS_MUSCULUS_NCBI_GRCM38", pathJoin(bowtie, "Mus_musculus", "NCBI", "GRCm38", _b))
pushenv ("BOWTIE2_MUS_MUSCULUS_NCBI_GRCM38", pathJoin(bowtie2, "Mus_musculus", "NCBI", "GRCm38", _b))
pushenv ("BWA_MUS_MUSCULUS_NCBI_GRCM38", pathJoin(bwa, "Mus_musculus", "NCBI", "GRCm38", _bwa))
pushenv ("PICARD_MUS_MUSCULUS_NCBI_GRCM38", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38", _w, _p))
pushenv ("FAIDX_MUS_MUSCULUS_NCBI_GRCM38", pathJoin(genomes, "Mus_musculus", "NCBI", "GRCm38", _w, _s))
pushenv ("MUS_MUSCULUS_UCSC_MM10", pathJoin(genomes, "Mus_musculus", "UCSC", "mm10"))
pushenv ("GENOME_MUS_MUSCULUS_UCSC_MM10", pathJoin(genomes, "Mus_musculus", "UCSC", "mm10", _w, _f))
pushenv ("CHR_MUS_MUSCULUS_UCSC_MM10", pathJoin(genomes, "Mus_musculus", "UCSC", "mm10", _c))
pushenv ("BOWTIE_MUS_MUSCULUS_UCSC_MM10", pathJoin(bowtie, "Mus_musculus", "UCSC", "mm10", _b))
pushenv ("BOWTIE2_MUS_MUSCULUS_UCSC_MM10", pathJoin(bowtie2, "Mus_musculus", "UCSC", "mm10", _b))
pushenv ("BWA_MUS_MUSCULUS_UCSC_MM10", pathJoin(bwa, "Mus_musculus", "UCSC", "mm10", _bwa))
pushenv ("PICARD_MUS_MUSCULUS_UCSC_MM10", pathJoin(genomes, "Mus_musculus", "UCSC", "mm10", _w, _p))
pushenv ("FAIDX_MUS_MUSCULUS_UCSC_MM10", pathJoin(genomes, "Mus_musculus", "UCSC", "mm10", _w, _s))
pushenv ("MUS_MUSCULUS_UCSC_MM9", pathJoin(genomes, "Mus_musculus", "UCSC", "mm9"))
pushenv ("GENOME_MUS_MUSCULUS_UCSC_MM9", pathJoin(genomes, "Mus_musculus", "UCSC", "mm9", _w, _f))
pushenv ("CHR_MUS_MUSCULUS_UCSC_MM9", pathJoin(genomes, "Mus_musculus", "UCSC", "mm9", _c))
pushenv ("BOWTIE_MUS_MUSCULUS_UCSC_MM9", pathJoin(bowtie, "Mus_musculus", "UCSC", "mm9", _b))
pushenv ("BOWTIE2_MUS_MUSCULUS_UCSC_MM9", pathJoin(bowtie2, "Mus_musculus", "UCSC", "mm9", _b))
pushenv ("BWA_MUS_MUSCULUS_UCSC_MM9", pathJoin(bwa, "Mus_musculus", "UCSC", "mm9", _bwa))
pushenv ("PICARD_MUS_MUSCULUS_UCSC_MM9", pathJoin(genomes, "Mus_musculus", "UCSC", "mm9", _w, _p))
pushenv ("FAIDX_MUS_MUSCULUS_UCSC_MM9", pathJoin(genomes, "Mus_musculus", "UCSC", "mm9", _w, _s))
pushenv ("MYCOBACTERIUM_TUBERCULOSIS_H37RV", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07"))
pushenv ("GENOME_MYCOBACTERIUM_TUBERCULOSIS_H37RV", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _w, _f))
pushenv ("CHR_MYCOBACTERIUM_TUBERCULOSIS_H37RV", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _c))
pushenv ("BOWTIE_MYCOBACTERIUM_TUBERCULOSIS_H37RV", pathJoin(bowtie, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _b))
pushenv ("BOWTIE2_MYCOBACTERIUM_TUBERCULOSIS_H37RV", pathJoin(bowtie2, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _b))
pushenv ("BWA_MYCOBACTERIUM_TUBERCULOSIS_H37RV", pathJoin(bwa, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _bwa))
pushenv ("PICARD_MYCOBACTERIUM_TUBERCULOSIS_H37RV", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _w, _p))
pushenv ("FAIDX_MYCOBACTERIUM_TUBERCULOSIS_H37RV", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _w, _s))
pushenv ("MYCOBACTERIUM_TUBERCULOSIS_H37RV_NCBI_2001_09_07", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07"))
pushenv ("GENOME_MYCOBACTERIUM_TUBERCULOSIS_H37RV_NCBI_2001_09_07", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _w, _f))
pushenv ("CHR_MYCOBACTERIUM_TUBERCULOSIS_H37RV_NCBI_2001_09_07", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _c))
pushenv ("BOWTIE_MYCOBACTERIUM_TUBERCULOSIS_H37RV_NCBI_2001_09_07", pathJoin(bowtie, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _b))
pushenv ("BOWTIE2_MYCOBACTERIUM_TUBERCULOSIS_H37RV_NCBI_2001_09_07", pathJoin(bowtie2, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _b))
pushenv ("BWA_MYCOBACTERIUM_TUBERCULOSIS_H37RV_NCBI_2001_09_07", pathJoin(bwa, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _bwa))
pushenv ("PICARD_MYCOBACTERIUM_TUBERCULOSIS_H37RV_NCBI_2001_09_07", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _w, _p))
pushenv ("FAIDX_MYCOBACTERIUM_TUBERCULOSIS_H37RV_NCBI_2001_09_07", pathJoin(genomes, "Mycobacterium_tuberculosis_H37RV", "NCBI", "2001-09-07", _w, _s))
pushenv ("OAR_RAMBOUILLET", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0"))
pushenv ("GENOME_OAR_RAMBOUILLET", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0", _w, _f))
pushenv ("CHR_OAR_RAMBOUILLET", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0", _c))
pushenv ("BOWTIE_OAR_RAMBOUILLET", pathJoin(bowtie, "Oar_rambouillet", "NCBI", "v2.0", _b))
pushenv ("BOWTIE2_OAR_RAMBOUILLET", pathJoin(bowtie2, "Oar_rambouillet", "NCBI", "v2.0", _b))
pushenv ("BWA_OAR_RAMBOUILLET", pathJoin(bwa, "Oar_rambouillet", "NCBI", "v2.0", _bwa))
pushenv ("PICARD_OAR_RAMBOUILLET", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0", _w, _p))
pushenv ("FAIDX_OAR_RAMBOUILLET", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0", _w, _s))
pushenv ("OAR_RAMBOUILLET_NCBI_V2_0", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0"))
pushenv ("GENOME_OAR_RAMBOUILLET_NCBI_V2_0", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0", _w, _f))
pushenv ("CHR_OAR_RAMBOUILLET_NCBI_V2_0", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0", _c))
pushenv ("BOWTIE_OAR_RAMBOUILLET_NCBI_V2_0", pathJoin(bowtie, "Oar_rambouillet", "NCBI", "v2.0", _b))
pushenv ("BOWTIE2_OAR_RAMBOUILLET_NCBI_V2_0", pathJoin(bowtie2, "Oar_rambouillet", "NCBI", "v2.0", _b))
pushenv ("BWA_OAR_RAMBOUILLET_NCBI_V2_0", pathJoin(bwa, "Oar_rambouillet", "NCBI", "v2.0", _bwa))
pushenv ("PICARD_OAR_RAMBOUILLET_NCBI_V2_0", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0", _w, _p))
pushenv ("FAIDX_OAR_RAMBOUILLET_NCBI_V2_0", pathJoin(genomes, "Oar_rambouillet", "NCBI", "v2.0", _w, _s))
pushenv ("RICE", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0"))
pushenv ("GENOME_RICE", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _w, _f))
pushenv ("CHR_RICE", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _c))
pushenv ("BOWTIE_RICE", pathJoin(bowtie, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _b))
pushenv ("BOWTIE2_RICE", pathJoin(bowtie2, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _b))
pushenv ("BWA_RICE", pathJoin(bwa, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _bwa))
pushenv ("PICARD_RICE", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _w, _p))
pushenv ("FAIDX_RICE", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _w, _s))
pushenv ("ORYZA_SATIVA_JAPONICA_ENSEMBL_IRGSP_1_0", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0"))
pushenv ("GENOME_ORYZA_SATIVA_JAPONICA_ENSEMBL_IRGSP_1_0", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _w, _f))
pushenv ("CHR_ORYZA_SATIVA_JAPONICA_ENSEMBL_IRGSP_1_0", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _c))
pushenv ("BOWTIE_ORYZA_SATIVA_JAPONICA_ENSEMBL_IRGSP_1_0", pathJoin(bowtie, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _b))
pushenv ("BOWTIE2_ORYZA_SATIVA_JAPONICA_ENSEMBL_IRGSP_1_0", pathJoin(bowtie2, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _b))
pushenv ("BWA_ORYZA_SATIVA_JAPONICA_ENSEMBL_IRGSP_1_0", pathJoin(bwa, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _bwa))
pushenv ("PICARD_ORYZA_SATIVA_JAPONICA_ENSEMBL_IRGSP_1_0", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _w, _p))
pushenv ("FAIDX_ORYZA_SATIVA_JAPONICA_ENSEMBL_IRGSP_1_0", pathJoin(genomes, "Oryza_sativa_japonica", "Ensembl", "IRGSP-1.0", _w, _s))
pushenv ("SHEEP", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1"))
pushenv ("GENOME_SHEEP", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1", _w, _f))
pushenv ("CHR_SHEEP", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1", _c))
pushenv ("BOWTIE_SHEEP", pathJoin(bowtie, "Ovis_aries", "NCBI", "Oar3_1", _b))
pushenv ("BOWTIE2_SHEEP", pathJoin(bowtie2, "Ovis_aries", "NCBI", "Oar3_1", _b))
pushenv ("BWA_SHEEP", pathJoin(bwa, "Ovis_aries", "NCBI", "Oar3_1", _bwa))
pushenv ("PICARD_SHEEP", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1", _w, _p))
pushenv ("FAIDX_SHEEP", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1", _w, _s))
pushenv ("OVIS_ARIES_NCBI_OAR3_1", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1"))
pushenv ("GENOME_OVIS_ARIES_NCBI_OAR3_1", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1", _w, _f))
pushenv ("CHR_OVIS_ARIES_NCBI_OAR3_1", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1", _c))
pushenv ("BOWTIE_OVIS_ARIES_NCBI_OAR3_1", pathJoin(bowtie, "Ovis_aries", "NCBI", "Oar3_1", _b))
pushenv ("BOWTIE2_OVIS_ARIES_NCBI_OAR3_1", pathJoin(bowtie2, "Ovis_aries", "NCBI", "Oar3_1", _b))
pushenv ("BWA_OVIS_ARIES_NCBI_OAR3_1", pathJoin(bwa, "Ovis_aries", "NCBI", "Oar3_1", _bwa))
pushenv ("PICARD_OVIS_ARIES_NCBI_OAR3_1", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1", _w, _p))
pushenv ("FAIDX_OVIS_ARIES_NCBI_OAR3_1", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar3_1", _w, _s))
pushenv ("OVIS_ARIES_NCBI_OAR4_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar4_0"))
pushenv ("GENOME_OVIS_ARIES_NCBI_OAR4_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar4_0", _w, _f))
pushenv ("CHR_OVIS_ARIES_NCBI_OAR4_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar4_0", _c))
pushenv ("BOWTIE_OVIS_ARIES_NCBI_OAR4_0", pathJoin(bowtie, "Ovis_aries", "NCBI", "Oar4_0", _b))
pushenv ("BOWTIE2_OVIS_ARIES_NCBI_OAR4_0", pathJoin(bowtie2, "Ovis_aries", "NCBI", "Oar4_0", _b))
pushenv ("BWA_OVIS_ARIES_NCBI_OAR4_0", pathJoin(bwa, "Ovis_aries", "NCBI", "Oar4_0", _bwa))
pushenv ("PICARD_OVIS_ARIES_NCBI_OAR4_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar4_0", _w, _p))
pushenv ("FAIDX_OVIS_ARIES_NCBI_OAR4_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar4_0", _w, _s))
pushenv ("OVIS_ARIES_NCBI_OAR_RAMBOUILLET_V1_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar_rambouillet_v1.0"))
pushenv ("GENOME_OVIS_ARIES_NCBI_OAR_RAMBOUILLET_V1_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar_rambouillet_v1.0", _w, _f))
pushenv ("CHR_OVIS_ARIES_NCBI_OAR_RAMBOUILLET_V1_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar_rambouillet_v1.0", _c))
pushenv ("BOWTIE_OVIS_ARIES_NCBI_OAR_RAMBOUILLET_V1_0", pathJoin(bowtie, "Ovis_aries", "NCBI", "Oar_rambouillet_v1.0", _b))
pushenv ("BOWTIE2_OVIS_ARIES_NCBI_OAR_RAMBOUILLET_V1_0", pathJoin(bowtie2, "Ovis_aries", "NCBI", "Oar_rambouillet_v1.0", _b))
pushenv ("BWA_OVIS_ARIES_NCBI_OAR_RAMBOUILLET_V1_0", pathJoin(bwa, "Ovis_aries", "NCBI", "Oar_rambouillet_v1.0", _bwa))
pushenv ("PICARD_OVIS_ARIES_NCBI_OAR_RAMBOUILLET_V1_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar_rambouillet_v1.0", _w, _p))
pushenv ("FAIDX_OVIS_ARIES_NCBI_OAR_RAMBOUILLET_V1_0", pathJoin(genomes, "Ovis_aries", "NCBI", "Oar_rambouillet_v1.0", _w, _s))
pushenv ("PAN_TROGLODYTES", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1"))
pushenv ("GENOME_PAN_TROGLODYTES", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1", _w, _f))
pushenv ("CHR_PAN_TROGLODYTES", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1", _c))
pushenv ("BOWTIE_PAN_TROGLODYTES", pathJoin(bowtie, "Pan_troglodytes", "NCBI", "build3.1", _b))
pushenv ("BOWTIE2_PAN_TROGLODYTES", pathJoin(bowtie2, "Pan_troglodytes", "NCBI", "build3.1", _b))
pushenv ("BWA_PAN_TROGLODYTES", pathJoin(bwa, "Pan_troglodytes", "NCBI", "build3.1", _bwa))
pushenv ("PICARD_PAN_TROGLODYTES", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1", _w, _p))
pushenv ("FAIDX_PAN_TROGLODYTES", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1", _w, _s))
pushenv ("PAN_TROGLODYTES_NCBI_BUILD3_1", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1"))
pushenv ("GENOME_PAN_TROGLODYTES_NCBI_BUILD3_1", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1", _w, _f))
pushenv ("CHR_PAN_TROGLODYTES_NCBI_BUILD3_1", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1", _c))
pushenv ("BOWTIE_PAN_TROGLODYTES_NCBI_BUILD3_1", pathJoin(bowtie, "Pan_troglodytes", "NCBI", "build3.1", _b))
pushenv ("BOWTIE2_PAN_TROGLODYTES_NCBI_BUILD3_1", pathJoin(bowtie2, "Pan_troglodytes", "NCBI", "build3.1", _b))
pushenv ("BWA_PAN_TROGLODYTES_NCBI_BUILD3_1", pathJoin(bwa, "Pan_troglodytes", "NCBI", "build3.1", _bwa))
pushenv ("PICARD_PAN_TROGLODYTES_NCBI_BUILD3_1", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1", _w, _p))
pushenv ("FAIDX_PAN_TROGLODYTES_NCBI_BUILD3_1", pathJoin(genomes, "Pan_troglodytes", "NCBI", "build3.1", _w, _s))
pushenv ("PHIX", pathJoin(genomes, "PhiX", "Illumina", "RTA"))
pushenv ("GENOME_PHIX", pathJoin(genomes, "PhiX", "Illumina", "RTA", _w, _f))
pushenv ("CHR_PHIX", pathJoin(genomes, "PhiX", "Illumina", "RTA", _c))
pushenv ("BOWTIE_PHIX", pathJoin(bowtie, "PhiX", "Illumina", "RTA", _b))
pushenv ("BOWTIE2_PHIX", pathJoin(bowtie2, "PhiX", "Illumina", "RTA", _b))
pushenv ("BWA_PHIX", pathJoin(bwa, "PhiX", "Illumina", "RTA", _bwa))
pushenv ("PICARD_PHIX", pathJoin(genomes, "PhiX", "Illumina", "RTA", _w, _p))
pushenv ("FAIDX_PHIX", pathJoin(genomes, "PhiX", "Illumina", "RTA", _w, _s))
pushenv ("PHIX_ILLUMINA_RTA", pathJoin(genomes, "PhiX", "Illumina", "RTA"))
pushenv ("GENOME_PHIX_ILLUMINA_RTA", pathJoin(genomes, "PhiX", "Illumina", "RTA", _w, _f))
pushenv ("CHR_PHIX_ILLUMINA_RTA", pathJoin(genomes, "PhiX", "Illumina", "RTA", _c))
pushenv ("BOWTIE_PHIX_ILLUMINA_RTA", pathJoin(bowtie, "PhiX", "Illumina", "RTA", _b))
pushenv ("BOWTIE2_PHIX_ILLUMINA_RTA", pathJoin(bowtie2, "PhiX", "Illumina", "RTA", _b))
pushenv ("BWA_PHIX_ILLUMINA_RTA", pathJoin(bwa, "PhiX", "Illumina", "RTA", _bwa))
pushenv ("PICARD_PHIX_ILLUMINA_RTA", pathJoin(genomes, "PhiX", "Illumina", "RTA", _w, _p))
pushenv ("FAIDX_PHIX_ILLUMINA_RTA", pathJoin(genomes, "PhiX", "Illumina", "RTA", _w, _s))
pushenv ("PSEUDOMONAS_AERUGINOSA_PAO1", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13"))
pushenv ("GENOME_PSEUDOMONAS_AERUGINOSA_PAO1", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _w, _f))
pushenv ("CHR_PSEUDOMONAS_AERUGINOSA_PAO1", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _c))
pushenv ("BOWTIE_PSEUDOMONAS_AERUGINOSA_PAO1", pathJoin(bowtie, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _b))
pushenv ("BOWTIE2_PSEUDOMONAS_AERUGINOSA_PAO1", pathJoin(bowtie2, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _b))
pushenv ("BWA_PSEUDOMONAS_AERUGINOSA_PAO1", pathJoin(bwa, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _bwa))
pushenv ("PICARD_PSEUDOMONAS_AERUGINOSA_PAO1", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _w, _p))
pushenv ("FAIDX_PSEUDOMONAS_AERUGINOSA_PAO1", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _w, _s))
pushenv ("PSEUDOMONAS_AERUGINOSA_PAO1_NCBI_2000_09_13", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13"))
pushenv ("GENOME_PSEUDOMONAS_AERUGINOSA_PAO1_NCBI_2000_09_13", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _w, _f))
pushenv ("CHR_PSEUDOMONAS_AERUGINOSA_PAO1_NCBI_2000_09_13", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _c))
pushenv ("BOWTIE_PSEUDOMONAS_AERUGINOSA_PAO1_NCBI_2000_09_13", pathJoin(bowtie, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _b))
pushenv ("BOWTIE2_PSEUDOMONAS_AERUGINOSA_PAO1_NCBI_2000_09_13", pathJoin(bowtie2, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _b))
pushenv ("BWA_PSEUDOMONAS_AERUGINOSA_PAO1_NCBI_2000_09_13", pathJoin(bwa, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _bwa))
pushenv ("PICARD_PSEUDOMONAS_AERUGINOSA_PAO1_NCBI_2000_09_13", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _w, _p))
pushenv ("FAIDX_PSEUDOMONAS_AERUGINOSA_PAO1_NCBI_2000_09_13", pathJoin(genomes, "Pseudomonas_aeruginosa_PAO1", "NCBI", "2000-09-13", _w, _s))
pushenv ("RAT", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0"))
pushenv ("GENOME_RAT", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _w, _f))
pushenv ("CHR_RAT", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _c))
pushenv ("BOWTIE_RAT", pathJoin(bowtie, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _b))
pushenv ("BOWTIE2_RAT", pathJoin(bowtie2, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _b))
pushenv ("BWA_RAT", pathJoin(bwa, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _bwa))
pushenv ("PICARD_RAT", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _w, _p))
pushenv ("FAIDX_RAT", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _w, _s))
pushenv ("RATTUS_NORVEGICUS_NCBI_RNOR_5_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0"))
pushenv ("GENOME_RATTUS_NORVEGICUS_NCBI_RNOR_5_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _w, _f))
pushenv ("CHR_RATTUS_NORVEGICUS_NCBI_RNOR_5_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _c))
pushenv ("BOWTIE_RATTUS_NORVEGICUS_NCBI_RNOR_5_0", pathJoin(bowtie, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _b))
pushenv ("BOWTIE2_RATTUS_NORVEGICUS_NCBI_RNOR_5_0", pathJoin(bowtie2, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _b))
pushenv ("BWA_RATTUS_NORVEGICUS_NCBI_RNOR_5_0", pathJoin(bwa, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _bwa))
pushenv ("PICARD_RATTUS_NORVEGICUS_NCBI_RNOR_5_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _w, _p))
pushenv ("FAIDX_RATTUS_NORVEGICUS_NCBI_RNOR_5_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_5.0", _w, _s))
pushenv ("RATTUS_NORVEGICUS_NCBI_RNOR_6_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_6.0"))
pushenv ("GENOME_RATTUS_NORVEGICUS_NCBI_RNOR_6_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_6.0", _w, _f))
pushenv ("CHR_RATTUS_NORVEGICUS_NCBI_RNOR_6_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_6.0", _c))
pushenv ("BOWTIE_RATTUS_NORVEGICUS_NCBI_RNOR_6_0", pathJoin(bowtie, "Rattus_norvegicus", "NCBI", "Rnor_6.0", _b))
pushenv ("BOWTIE2_RATTUS_NORVEGICUS_NCBI_RNOR_6_0", pathJoin(bowtie2, "Rattus_norvegicus", "NCBI", "Rnor_6.0", _b))
pushenv ("BWA_RATTUS_NORVEGICUS_NCBI_RNOR_6_0", pathJoin(bwa, "Rattus_norvegicus", "NCBI", "Rnor_6.0", _bwa))
pushenv ("PICARD_RATTUS_NORVEGICUS_NCBI_RNOR_6_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_6.0", _w, _p))
pushenv ("FAIDX_RATTUS_NORVEGICUS_NCBI_RNOR_6_0", pathJoin(genomes, "Rattus_norvegicus", "NCBI", "Rnor_6.0", _w, _s))
pushenv ("YEAST", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1"))
pushenv ("GENOME_YEAST", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _w, _f))
pushenv ("CHR_YEAST", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _c))
pushenv ("BOWTIE_YEAST", pathJoin(bowtie, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _b))
pushenv ("BOWTIE2_YEAST", pathJoin(bowtie2, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _b))
pushenv ("BWA_YEAST", pathJoin(bwa, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _bwa))
pushenv ("PICARD_YEAST", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _w, _p))
pushenv ("FAIDX_YEAST", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _w, _s))
pushenv ("SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3_1", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1"))
pushenv ("GENOME_SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3_1", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _w, _f))
pushenv ("CHR_SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3_1", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _c))
pushenv ("BOWTIE_SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3_1", pathJoin(bowtie, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _b))
pushenv ("BOWTIE2_SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3_1", pathJoin(bowtie2, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _b))
pushenv ("BWA_SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3_1", pathJoin(bwa, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _bwa))
pushenv ("PICARD_SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3_1", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _w, _p))
pushenv ("FAIDX_SACCHAROMYCES_CEREVISIAE_NCBI_BUILD3_1", pathJoin(genomes, "Saccharomyces_cerevisiae", "NCBI", "build3.1", _w, _s))
pushenv ("SCIURUS_CAROLINENSIS", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2"))
pushenv ("GENOME_SCIURUS_CAROLINENSIS", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2", _w, _f))
pushenv ("CHR_SCIURUS_CAROLINENSIS", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2", _c))
pushenv ("BOWTIE_SCIURUS_CAROLINENSIS", pathJoin(bowtie, "Sciurus_carolinensis", "NCBI", "1.2", _b))
pushenv ("BOWTIE2_SCIURUS_CAROLINENSIS", pathJoin(bowtie2, "Sciurus_carolinensis", "NCBI", "1.2", _b))
pushenv ("BWA_SCIURUS_CAROLINENSIS", pathJoin(bwa, "Sciurus_carolinensis", "NCBI", "1.2", _bwa))
pushenv ("PICARD_SCIURUS_CAROLINENSIS", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2", _w, _p))
pushenv ("FAIDX_SCIURUS_CAROLINENSIS", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2", _w, _s))
pushenv ("SCIURUS_CAROLINENSIS_NCBI_1_2", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2"))
pushenv ("GENOME_SCIURUS_CAROLINENSIS_NCBI_1_2", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2", _w, _f))
pushenv ("CHR_SCIURUS_CAROLINENSIS_NCBI_1_2", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2", _c))
pushenv ("BOWTIE_SCIURUS_CAROLINENSIS_NCBI_1_2", pathJoin(bowtie, "Sciurus_carolinensis", "NCBI", "1.2", _b))
pushenv ("BOWTIE2_SCIURUS_CAROLINENSIS_NCBI_1_2", pathJoin(bowtie2, "Sciurus_carolinensis", "NCBI", "1.2", _b))
pushenv ("BWA_SCIURUS_CAROLINENSIS_NCBI_1_2", pathJoin(bwa, "Sciurus_carolinensis", "NCBI", "1.2", _bwa))
pushenv ("PICARD_SCIURUS_CAROLINENSIS_NCBI_1_2", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2", _w, _p))
pushenv ("FAIDX_SCIURUS_CAROLINENSIS_NCBI_1_2", pathJoin(genomes, "Sciurus_carolinensis", "NCBI", "1.2", _w, _s))
pushenv ("SCIURUS_VULGARIS", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1"))
pushenv ("GENOME_SCIURUS_VULGARIS", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _w, _f))
pushenv ("CHR_SCIURUS_VULGARIS", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _c))
pushenv ("BOWTIE_SCIURUS_VULGARIS", pathJoin(bowtie, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _b))
pushenv ("BOWTIE2_SCIURUS_VULGARIS", pathJoin(bowtie2, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _b))
pushenv ("BWA_SCIURUS_VULGARIS", pathJoin(bwa, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _bwa))
pushenv ("PICARD_SCIURUS_VULGARIS", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _w, _p))
pushenv ("FAIDX_SCIURUS_VULGARIS", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _w, _s))
pushenv ("SCIURUS_VULGARIS_ENSEMBL_MSCIVUL1_1", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1"))
pushenv ("GENOME_SCIURUS_VULGARIS_ENSEMBL_MSCIVUL1_1", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _w, _f))
pushenv ("CHR_SCIURUS_VULGARIS_ENSEMBL_MSCIVUL1_1", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _c))
pushenv ("BOWTIE_SCIURUS_VULGARIS_ENSEMBL_MSCIVUL1_1", pathJoin(bowtie, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _b))
pushenv ("BOWTIE2_SCIURUS_VULGARIS_ENSEMBL_MSCIVUL1_1", pathJoin(bowtie2, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _b))
pushenv ("BWA_SCIURUS_VULGARIS_ENSEMBL_MSCIVUL1_1", pathJoin(bwa, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _bwa))
pushenv ("PICARD_SCIURUS_VULGARIS_ENSEMBL_MSCIVUL1_1", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _w, _p))
pushenv ("FAIDX_SCIURUS_VULGARIS_ENSEMBL_MSCIVUL1_1", pathJoin(genomes, "Sciurus_vulgaris", "Ensembl", "mSciVul1.1", _w, _s))
pushenv ("SORGHUM", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1"))
pushenv ("GENOME_SORGHUM", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1", _w, _f))
pushenv ("CHR_SORGHUM", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1", _c))
pushenv ("BOWTIE_SORGHUM", pathJoin(bowtie, "Sorghum_bicolor", "Ensembl", "Sbi1", _b))
pushenv ("BOWTIE2_SORGHUM", pathJoin(bowtie2, "Sorghum_bicolor", "Ensembl", "Sbi1", _b))
pushenv ("BWA_SORGHUM", pathJoin(bwa, "Sorghum_bicolor", "Ensembl", "Sbi1", _bwa))
pushenv ("PICARD_SORGHUM", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1", _w, _p))
pushenv ("FAIDX_SORGHUM", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1", _w, _s))
pushenv ("SORGHUM_BICOLOR_ENSEMBL_SBI1", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1"))
pushenv ("GENOME_SORGHUM_BICOLOR_ENSEMBL_SBI1", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1", _w, _f))
pushenv ("CHR_SORGHUM_BICOLOR_ENSEMBL_SBI1", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1", _c))
pushenv ("BOWTIE_SORGHUM_BICOLOR_ENSEMBL_SBI1", pathJoin(bowtie, "Sorghum_bicolor", "Ensembl", "Sbi1", _b))
pushenv ("BOWTIE2_SORGHUM_BICOLOR_ENSEMBL_SBI1", pathJoin(bowtie2, "Sorghum_bicolor", "Ensembl", "Sbi1", _b))
pushenv ("BWA_SORGHUM_BICOLOR_ENSEMBL_SBI1", pathJoin(bwa, "Sorghum_bicolor", "Ensembl", "Sbi1", _bwa))
pushenv ("PICARD_SORGHUM_BICOLOR_ENSEMBL_SBI1", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1", _w, _p))
pushenv ("FAIDX_SORGHUM_BICOLOR_ENSEMBL_SBI1", pathJoin(genomes, "Sorghum_bicolor", "Ensembl", "Sbi1", _w, _s))
pushenv ("STAPHYLOCOCCUS_AUREUS_NCTC_8325", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13"))
pushenv ("GENOME_STAPHYLOCOCCUS_AUREUS_NCTC_8325", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _w, _f))
pushenv ("CHR_STAPHYLOCOCCUS_AUREUS_NCTC_8325", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _c))
pushenv ("BOWTIE_STAPHYLOCOCCUS_AUREUS_NCTC_8325", pathJoin(bowtie, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _b))
pushenv ("BOWTIE2_STAPHYLOCOCCUS_AUREUS_NCTC_8325", pathJoin(bowtie2, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _b))
pushenv ("BWA_STAPHYLOCOCCUS_AUREUS_NCTC_8325", pathJoin(bwa, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _bwa))
pushenv ("PICARD_STAPHYLOCOCCUS_AUREUS_NCTC_8325", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _w, _p))
pushenv ("FAIDX_STAPHYLOCOCCUS_AUREUS_NCTC_8325", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _w, _s))
pushenv ("STAPHYLOCOCCUS_AUREUS_NCTC_8325_NCBI_2006_02_13", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13"))
pushenv ("GENOME_STAPHYLOCOCCUS_AUREUS_NCTC_8325_NCBI_2006_02_13", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _w, _f))
pushenv ("CHR_STAPHYLOCOCCUS_AUREUS_NCTC_8325_NCBI_2006_02_13", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _c))
pushenv ("BOWTIE_STAPHYLOCOCCUS_AUREUS_NCTC_8325_NCBI_2006_02_13", pathJoin(bowtie, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _b))
pushenv ("BOWTIE2_STAPHYLOCOCCUS_AUREUS_NCTC_8325_NCBI_2006_02_13", pathJoin(bowtie2, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _b))
pushenv ("BWA_STAPHYLOCOCCUS_AUREUS_NCTC_8325_NCBI_2006_02_13", pathJoin(bwa, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _bwa))
pushenv ("PICARD_STAPHYLOCOCCUS_AUREUS_NCTC_8325_NCBI_2006_02_13", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _w, _p))
pushenv ("FAIDX_STAPHYLOCOCCUS_AUREUS_NCTC_8325_NCBI_2006_02_13", pathJoin(genomes, "Staphylococcus_aureus_NCTC_8325", "NCBI", "2006-02-13", _w, _s))
pushenv ("PIG", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2"))
pushenv ("GENOME_PIG", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2", _w, _f))
pushenv ("CHR_PIG", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2", _c))
pushenv ("BOWTIE_PIG", pathJoin(bowtie, "Sus_scrofa", "NCBI", "Sscrofa10.2", _b))
pushenv ("BOWTIE2_PIG", pathJoin(bowtie2, "Sus_scrofa", "NCBI", "Sscrofa10.2", _b))
pushenv ("BWA_PIG", pathJoin(bwa, "Sus_scrofa", "NCBI", "Sscrofa10.2", _bwa))
pushenv ("PICARD_PIG", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2", _w, _p))
pushenv ("FAIDX_PIG", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2", _w, _s))
pushenv ("SUS_SCROFA_NCBI_SSCROFA10_2", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2"))
pushenv ("GENOME_SUS_SCROFA_NCBI_SSCROFA10_2", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2", _w, _f))
pushenv ("CHR_SUS_SCROFA_NCBI_SSCROFA10_2", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2", _c))
pushenv ("BOWTIE_SUS_SCROFA_NCBI_SSCROFA10_2", pathJoin(bowtie, "Sus_scrofa", "NCBI", "Sscrofa10.2", _b))
pushenv ("BOWTIE2_SUS_SCROFA_NCBI_SSCROFA10_2", pathJoin(bowtie2, "Sus_scrofa", "NCBI", "Sscrofa10.2", _b))
pushenv ("BWA_SUS_SCROFA_NCBI_SSCROFA10_2", pathJoin(bwa, "Sus_scrofa", "NCBI", "Sscrofa10.2", _bwa))
pushenv ("PICARD_SUS_SCROFA_NCBI_SSCROFA10_2", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2", _w, _p))
pushenv ("FAIDX_SUS_SCROFA_NCBI_SSCROFA10_2", pathJoin(genomes, "Sus_scrofa", "NCBI", "Sscrofa10.2", _w, _s))
pushenv ("MAIZE", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3"))
pushenv ("GENOME_MAIZE", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3", _w, _f))
pushenv ("CHR_MAIZE", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3", _c))
pushenv ("BOWTIE_MAIZE", pathJoin(bowtie, "Zea_mays", "Ensembl", "AGPv3", _b))
pushenv ("BOWTIE2_MAIZE", pathJoin(bowtie2, "Zea_mays", "Ensembl", "AGPv3", _b))
pushenv ("BWA_MAIZE", pathJoin(bwa, "Zea_mays", "Ensembl", "AGPv3", _bwa))
pushenv ("PICARD_MAIZE", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3", _w, _p))
pushenv ("FAIDX_MAIZE", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3", _w, _s))
pushenv ("ZEA_MAYS_ENSEMBL_AGPV3", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3"))
pushenv ("GENOME_ZEA_MAYS_ENSEMBL_AGPV3", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3", _w, _f))
pushenv ("CHR_ZEA_MAYS_ENSEMBL_AGPV3", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3", _c))
pushenv ("BOWTIE_ZEA_MAYS_ENSEMBL_AGPV3", pathJoin(bowtie, "Zea_mays", "Ensembl", "AGPv3", _b))
pushenv ("BOWTIE2_ZEA_MAYS_ENSEMBL_AGPV3", pathJoin(bowtie2, "Zea_mays", "Ensembl", "AGPv3", _b))
pushenv ("BWA_ZEA_MAYS_ENSEMBL_AGPV3", pathJoin(bwa, "Zea_mays", "Ensembl", "AGPv3", _bwa))
pushenv ("PICARD_ZEA_MAYS_ENSEMBL_AGPV3", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3", _w, _p))
pushenv ("FAIDX_ZEA_MAYS_ENSEMBL_AGPV3", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv3", _w, _s))
pushenv ("ZEA_MAYS_ENSEMBL_AGPV4", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv4"))
pushenv ("GENOME_ZEA_MAYS_ENSEMBL_AGPV4", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv4", _w, _f))
pushenv ("CHR_ZEA_MAYS_ENSEMBL_AGPV4", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv4", _c))
pushenv ("BOWTIE_ZEA_MAYS_ENSEMBL_AGPV4", pathJoin(bowtie, "Zea_mays", "Ensembl", "AGPv4", _b))
pushenv ("BOWTIE2_ZEA_MAYS_ENSEMBL_AGPV4", pathJoin(bowtie2, "Zea_mays", "Ensembl", "AGPv4", _b))
pushenv ("BWA_ZEA_MAYS_ENSEMBL_AGPV4", pathJoin(bwa, "Zea_mays", "Ensembl", "AGPv4", _bwa))
pushenv ("PICARD_ZEA_MAYS_ENSEMBL_AGPV4", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv4", _w, _p))
pushenv ("FAIDX_ZEA_MAYS_ENSEMBL_AGPV4", pathJoin(genomes, "Zea_mays", "Ensembl", "AGPv4", _w, _s))
pushenv("GENOME_BACTERIAL", pathJoin(genomes, "all_complete_bacterial_genome.fasta"))
pushenv("BOWTIE2_BACTERIAL", pathJoin(bowtie2, "all_complete_bacterial_genome"))
pushenv("BWA_BACTERIAL", pathJoin(bwa, "all_complete_bacterial_genome"))
pushenv("FAIDX_BACTERIAL", pathJoin(genomes, "all_complete_bacterial_genome.fasta.fai"))
pushenv("BLAST_BACTERIAL", pathJoin(blast_v4, "genomic_bacterial_complete_only"))

-- Same for all bacteria, incl. incomplete. Please note there are no bowtie or bwa
-- indices for these due to the sheer size.
pushenv("GENOME_BACTERIAL_ALL", pathJoin(genomes, "all_bacterial_genomes.fasta"))
pushenv("FAIDX_BACTERIAL_ALL", pathJoin(genomes, "all_bacterial_genomes.fasta.fai"))
pushenv("BLAST_BACTERIAL_ALL", pathJoin(blast_v4, "genomic_bacterial"))
pushenv("GENOME_ARCHAEA", pathJoin(genomes, "all_complete_archaea_genome.fasta"))
pushenv("BOWTIE2_ARCHAEA", pathJoin(bowtie2, "all_complete_archaea_genome"))
pushenv("BWA_ARCHAEA", pathJoin(bwa, "all_complete_archaea_genome"))
pushenv("FAIDX_ARCHAEA", pathJoin(genomes, "all_complete_archaea_genome.fasta.fai"))
pushenv("BLAST_ARCHAEA", pathJoin(blast_v4, "genomic_archaea_complete_only"))
pushenv("GENOME_ARCHAEA_ALL", pathJoin(genomes, "all_archaea_genome.fasta"))
pushenv("BOWTIE2_ARCHAEA_ALL", pathJoin(bowtie2, "all_archaea_genome"))
pushenv("BWA_ARCHAEA_ALL", pathJoin(bwa, "all_archaea_genome"))
pushenv("FAIDX_ARCHAEA_ALL", pathJoin(genomes, "all_archaea_genome.fasta.fai"))
pushenv("BLAST_ARCHAEA_ALL", pathJoin(blast_v4, "genomic_archaea"))

if (mode() == "load") then
        LmodMessage("Static data resources for bioinformatics 1.0.")
        LmodMessage("     Contact the Bioinformatics Core Research Facility (bcrf-support@unl.edu) for questions/support.")
        LmodMessage("     NOTE: use $BLAST_V4 for access to blast databases when using NCBI blast <= 2.9")
        LmodMessage("     NOTE 2: $BLAST_V4 databases will not be updated going forward.")
end

