help(
[[
This module loads Connectome-workbench.
Version 1.3.1
]]
)
whatis("Name: Connectome-workbench")
whatis("Version: 1.3.1")
whatis("Category: neuroimaging, biology")
whatis("Keywords: Neuroimaging, Biology ")
whatis("URL: https://www.humanconnectome.org/software/connectome-workbench")
whatis("Description: Connectome Workbench is an open source, freely available visualization and discovery tool used to map neuroimaging data, especially data generated by the Human Connectome Project")

pushenv("CONDA_DEFAULT_ENV", "connectome-workbench-1.3.1")
append_path("CONDA_ENVS_PATH", "/util/opt/anaconda/deployed-conda-envs/packages/connectome-workbench/envs")
prepend_path("PATH", "/util/opt/anaconda/deployed-conda-envs/packages/connectome-workbench/envs/connectome-workbench-1.3.1/bin")
