help(
[[
This module loads NextPolish.
Version 1.4.1
]]
)

whatis("Name: NextPolish")
whatis("Version: 1.4.1")
whatis("Category: computational biology, long reads")
whatis("Keywords: computational biology, SNV, indel")
whatis("URL: https://github.com/Nextomics/NextPolish")
whatis("Description: Fast and accurately polish the genome generated by long reads")

pushenv("CONDA_DEFAULT_ENV", "nextpolish-1.4.1")
append_path("CONDA_ENVS_PATH", "/util/opt/anaconda/deployed-conda-envs/packages/nextpolish/envs")
prepend_path("PATH", "/util/opt/anaconda/deployed-conda-envs/packages/nextpolish/envs/nextpolish-1.4.1/bin")

family("python")
